### ISSUE TITLE
PythonInput.on_reset()

### ISSUE THREAD

**Issue by 38elements** [jonathanslenders/ptpython#102]
[KeyBindingManager.reset()](https://github.com/jonathanslenders/python-prompt-toolkit/blob/9927cbe6a5a125847584c83b5b02574f4270538f/prompt_toolkit/key_binding/manager.py#L153) is in need of a parameter.
It does not pass a variable as follows in [PythonInput.on_reset()](https://github.com/jonathanslenders/ptpython/blob/f9bca69af7b7823146af744493906f89260ea75e/ptpython/python_input.py#L617-L619).
```
    def on_reset(self, cli):
        self.key_bindings_manager.reset()
        self.signatures = []
```
Maybe, `PythonInput.on_reset()` may not have been used.

**Comment by jonathanslenders** [comment]
Thank you! This is a bug. I'll fix it asap.

**Comment by 38elements** [comment]
#101
