### ISSUE TITLE
executed commands in ptipython is copied onto next line

### ISSUE THREAD

**Issue by ned2** [jonathanslenders/ptpython#114]
After executing a command inside of `ptipython`, the command is copied onto the next prompt line, making the REPL unusable as the line has to be deleted before new input can be performed. I've got the same behaviour happening on both Ubuntu 16.04 and 15.10 and in both Python 2 and 3. The problem is not happening with vanilla `ptpython`

**Comment by jonathanslenders** [comment]
Hi @ned2,

Thanks for reporting this issue. It's fixed in https://github.com/jonathanslenders/ptpython/commit/3f3125e73bcfbf3c7172dbbfeb59ecc722ca479c
And I just pushed a new releas: 0.34

**Comment by ned2** [comment]
Wow, that's some pretty great turnaround time. Thanks!
