### ISSUE TITLE
Updates to pip repository ....

### ISSUE THREAD

**Issue by nmvega** [jonathanslenders/ptpython#115]
Hi Jonathan:

I was wondering how often updates here are submitted to the PIP repository. I think there have been updates here (I could be wrong), but notice during '_conda-updates_' (the Andconda Python update tool), that they are not reflected in the PIP repository. Should I just update manually from here instead?

Thank you! =:)

**Comment by stonebig** [comment]
ptpython-0.34 is already on pip

**Comment by nmvega** [comment]
Hi @stonebig. I see that now that you mention it. Anaconda has up to 0.32 (currently); but you're correct, explicitly running **pip install --upgrade ptpython** got me to 0.34. I'll use that method then. Thank you for the reply.

**Comment by stonebig** [comment]
you may close your issue, if you consider the problem solved.

**Comment by nmvega** [comment]
Closed. Thank you.
