### ISSUE TITLE
How Do I Map Vi <ESC> to jj?

### ISSUE THREAD

**Issue by austincrft** [jonathanslenders/ptpython#118]
In Vim, I use the mapping `imap jj <Esc>`.

Is there a way to do this using `~/.ptpython/config.py`? I couldn't get it working using the example keybindings.

**Comment by jonathanslenders** [comment]
Hi @austincrft,

Thanks for the suggestion. Right now there is no way yet to do this in prompt-toolkit. I'll put it on my to-do list. It's an interesting challenge.  (It needs a few more changes. You want to see the first 'j' when that is pressed, but hide that again if another 'j' is pressed.)

**Comment by austincrft** [comment]
Great! Should this be moved to the prompt-toolkit repo instead? I'd be interested in helping with a PR, if you'd like.

**Comment by jonathanslenders** [comment]
Hi @austincrft,

This has been done. Please update to the latest prompt-toolkit (by checking out from git) and ptpython.

Then have a look at this example:
https://github.com/jonathanslenders/ptpython/commit/bdaf4773ba6ac16b7119c511ba9a3926f14d4d41

Normally that should do it.
