### ISSUE TITLE
ptpython hangs pasting large string

### ISSUE THREAD

**Issue by dakra** [jonathanslenders/ptpython#119]
Enter/copy this in ptpython freezes:

``
"""Ynchm51ACAAAA+HRSTlMAAQIDBAUGBwgJCgsMDQ4PEBESExQVFhcYGhscHR4fICEiIyQlJicoKSorLC0uL\
zAxMjM0NTY3ODk6Ozw9Pj9AQUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVpbXF1eX2BhYmNkZWZnaGlqa21ucHFyc3\
R1dnd4eXp8fX5/gIGCg4SFhoeIiYqLjI2Oj5CRkpOUlZaXmJmanZ6foKGio6SlpqeoqaqrrK2ur7CxsrO0tba3uLm\
6u72+v8DBwsPExcbHyMnKy8zNzs/Q0dLT1NXW19jZ2tvc3d7f4OHi4+Tl5ufo6err7O3u7/Dx8vP09fb3+Pn6+/z9\
/k//w+EAAAfzSURBVHgBYiAZKM642yXGMOzAsh8/fnQPO1/xfgZ668Ww85bEDxAY9dbgAKPeGvXWqLdGvTXqLUAtd\
h8e05n+Afw7M4kgkyBIfopKvBMVfqKtra2WtVZX6yUVKkgsbdFtqy0bSlmKrpfYZavbra7d2lqiFKmuYku87G5bBO\
uFaDakdkkJJUkz95973fecnHnOmedcM9c1k88/mfOcXDPne87zPOd+nthuI+cUvD4jq13oWOm5ubl9ECSuQ+bwy\
a8sndAI4eg9afbqdfOmDoqBXcJPZyxav/yl7LbQiIee7lyTvMIztWQ4tao3xMCiipXxwbHcRcT+FguLPr+9SX5b4cC\
V//WhLLCOay6ToXLjQCjcEz+pJsPf5yTYL3RTbUkvp/u+t25vDwQkr7pBFr5NXbj9HBHNCI41kv\
yyEeCddoxMtY3BkmA3mIhueQHMqiHVljTU++EXpKqY6oZqMrfdBx3vCSLajHru6ZUU5PvXgL784XBwrHzy+yVMeVWkq\
E0BkFNGV6bC6h0+Ox7oU0tWN4fAb76PbLY2geJX3HQkzqkSp29hSCkmrXWeQfznTHCs1neJ1ZqD0LOaLFYCGEpsNCw2\
cdvzwAyyqxkH1p+CHW2OgB73uOl3sDFv9gfw63SBDDcOvz93+pKNxXXkt+1xh1jotmrfvn0F3WBI+pQMF3e8\
88bzTyab94726GP1rSGq3jFzeMaQaSuukLjTGQDWE7uwKOeRflmv7vKReB+KKcRmwm64XHZpK4jMayTqNnaFod1cI2m\
RPpZdz/NGv/1oqAumfcS+1MdC5rKxzeEXm32JWLEHwMtEdPonbvh1fJvEU1CslYc7EFadZSB9lwGR+i0x3+YeULhfuU\
cinFgdrpN4+36oFhNbo49l1fogsV8ASF5/fKE6S+fJ1FLRUn0PHeCmb9pC5S0hNh4i9gix8kzYPHA83FiN/0Gs9\
llYxXN7SVI4sRAns2j1Awg2mtifoUgpkxHXGAGurcTeUucVOtsBQeIPhxlrLbHKwbCLnfLWtKYIKxZ6yUNZB41NxFKgy\
JS+9HsEzCX2qQfiIRmTl5Oh0fJ0WLHSZaTe6g5nrtCxsNz6U4rWt/nUOKhyib2Aek/IRVxMgt92Ge\
mPQKt9RTixdugmJkXSwTufJYeO1YNYG2h8yGfWw+LX0u8fhV8XmSBu1/fhnvKwFsDBC2HE6kes2A0ne4joZOhYkL4xA\
RrZfOYcLGL2c+O1dmAJp4iNhWEDH/23KRw0vhI61kqZbXvBkUz+GaFjreAzy6CRSKwJLJK/ljer9PFtxJbC4\
JHKdD4c5YeM5ZJvXwNnX0mVFTrWz/nMu9CRerU9rPpxpVPOn14nVuSGob+MrFZwNDhkrAHE+sOZPM7ToWNl8Zkd0DnJ\
p/4fNjk+ogIAI2QknW+BenP4+BicDQoZa6HMpFC0zHpxiDrSHieWFjLWD6xltUpKs2GwG1U4ywt0lS5XlQ7TTm5YHl\
GsP0h5ob49ueQobgdTrJT2g0PGypB7Dh0ZOznQSjwjRdIYBPxT1kwRxZI6ZrZSnNQSO+CGScqVyeHFKnWO\
lQsd13bLCklIhfnjiGKVKoUY20h+A2GSejm/gWItILbTDYW8xAZEFEs69o9g+pL8XoLpPT4uaJhYT/mk9msGVXXkseSBP\
20brtauvYWP32iQWN1v6Qq38zIUI4p11HaZU0lUtoZJ1gjTGyJWs3/JdDESVp/I2ziiWLu4ZQkCZIFQrRZB5dwysg\
FiuXaQ2RFU67j144hiFciGifpbP9v91bvquimNWP8GiLWI2HYX4J3UGwHT5c42jyTWE9xSlwRnL8t2UKPoxxrlk/o\
lEWh7g3zTYfo/WaXkRRIrvlp/nbY320ZEPVYPmS5udgUwj2/tUJj28pnjnghi+b/iUgyc9Jd7OirqsZqfleliBH+eL\
dtmaaj3LLEZkcQaR2wKnBySvbIm0Y7l3klsHljiBXk88TAkyvr3euswY6UQ80DlLpGvaA+9icSWIdqxFhMrd\
EH0kn2BD1Evj9ixhPBixcpYbKN7XIdiodNXfu9qQrRjjZGuXWJ+71hic2BwHSH217iwYuHffPwgLNzHiP1Rl+u\
+cmK5iHKsnlXyzu8M01KZkYfBkFlD7KNmYcU6qFvJpFYSK/LCbkAZsQOuKMdqfk5CDFdvbpFMG51gyK4jVv5kOL\
FWy95HG3u9SeLkY7CIebWG2NlWiG4s925i+VC1kErwhNdWxdEmpXOlv1m0PUUTqzuxY21htZD8tijVhWfSeRLXOiHK\
sd4k9hdYpd+2ts4iw/lFg7okIjEzb78UVZpY+IxY1doJaW4oXqwjv1MLHkuNQYuuz2y4Sn7/eRBRjvU0sRPxsMmyPc\
OZdyjgLhm+0MXKMP+1bDwUo78j0/c1ZJLlf3RjdZKncqMjgiwha7WRuoeCFQF4VN01EtlkSoWi937SKYiF1Qfc+hw0e\
ku5Ap1CddtgtVy8bk3v3mU8DlPudbI52wWA92bQNvEE8z/HwGLMRbLb1gd2z3F7OjQafSO1o+MWYmd1zLwGHZkhS6Dw\
ji+8RwGfP9MIbKGPKm3XlrLhDrGKOFjFTfxY7X6Vf+qDYAll0g908n1UNVB/uaVEhTC0vCxbXVrdr1Ld\
NFgl5vxmS3Hp3fID780NzGj3ZzWBXdMxKzZ/vjgNwVrkrd9dUlV16ejO+Q97oOUZ8TAcpOYkQM89LAOmmFEPw\
UlSdir+B2hn2K7/vBBtAAAAAElFTkSuQmCC\
"""``

**Comment by jonathanslenders** [comment]
Thanks for reporting this bug!
I think that the following commit fixes this issue: https://github.com/jonathanslenders/ptpython/commit/aadb371d22ac869e3a5495402f887b465bcf3818

**Comment by dakra** [comment]
Just realized I never replied.
The string works fine in the latest version.
Thanks
