### ISSUE TITLE
terminal scrolling

### ISSUE THREAD

**Issue by twice** [jonathanslenders/ptpython#121]
I'm using iterm2, the problem I have is that terminal scrolling does not seem to work. This is problematic for long outputs. I can't seem to find my way out using vi navigation.

**Comment by Heckle1** [comment]
I have to switch between _mouse support_ to scroll documentation/history and ability to select text to do a copy for instance. Emacs or VI mode.
I am using iTerm2.

**Comment by jonathanslenders** [comment]
Could you try to hold shift, option, control or alt while scrolling? (Or any of those combinations)
Does that work? Normally, mouse support does not need to be disabled in order to scroll the terminal.

**Comment by twice** [comment]
Thanks a lot. Holding alt seems to work.

**Comment by garettmd** [comment]
Is this behavior by design (where I _have_ to hold down the alt key to be able to select or scroll)?

**Comment by jonathanslenders** [comment]
When mouse support has been enabled, all mouse events are captured, including scroll events. That way, the application running in the terminal can decide what to do with it. You can disable mouse support.
Holding alt down tells the terminal to use the real scrollbar and move the up.

**Comment by garettmd** [comment]
Ok, that makes sense. Thanks

**Comment by mutecamel** [comment]
When using Terminal.app on macOS, one needs to press `fn` key while scrolling.
