### ISSUE TITLE
Installing both python2 and python3 versions

### ISSUE THREAD

**Issue by dnivra** [jonathanslenders/ptpython#122]
Is it possible to have separate installations of pyt[i]python for Python 2 and Python 3 like how IPython does it(ipython2 vs ipython3) while also having a default ipython(which will be the last installed version)? Right now, pt[i]python defaults to the latest installed version(I'm using pip).

**Comment by jonathanslenders** [comment]
Very good suggestion. It should be possible to add ``ptpython2`` and ``ptpython3`` commands to the setup.py

**Comment by dnivra** [comment]
Closing issue since it's been fixed in [version 0.35](https://github.com/jonathanslenders/ptpython/commits/0.35).
