### ISSUE TITLE
ptipython does not clear line after execution

### ISSUE THREAD

**Issue by c4traz** [jonathanslenders/ptpython#127]
I'm using pt**i**python 0.33 in a ssh session on a Ubuntu 14.04.3 LTS server and experience weird behavior.
After executing a line, I have to manually remove what I entered as the command remains in the new line:

```
$ ptipython
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
Type "copyright", "credits" or "license" for more information.

IPython 4.1.2 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: 1+1
Out[1]: 2

In [2]: 1+1  <-- anything entered in previous line still appears as if newly entered on following line
```

ptpython is not doing it, also ipython is not doing it.

My config file: [config.py.txt](https://github.com/jonathanslenders/ptpython/files/346292/config.py.txt)

**Comment by jonathanslenders** [comment]
Hi @c4traz,

Sorry to reply this late. Is the above issue still the case for the latest prompt-toolkit and latest ptpython?

**Comment by c4traz** [comment]
Ah, upgrading to 0.35 solved the problem. Thank you very much @jonathanslenders! I really enjoy working with ptpython.

**Comment by jonathanslenders** [comment]
Cool! Thanks :-)
