### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0x85 in position 0: ordinal

### ISSUE THREAD

**Issue by sametmax** [jonathanslenders/ptpython#13]
Typing class Test(object\<tab\> :

```

class Test(objectTraceback (most recent call last):
  File "C:\Python27\Scripts\ptpython-script.py", line 9, in <module>
    load_entry_point('ptpython==0.4', 'console_scripts', 'ptpython')()
  File "C:\Python27\lib\site-packages\ptpython\entry_points\run_ptpython.py", line 62, in run
    no_colors=no_colors, startup_paths=startup_paths)
  File "C:\Python27\lib\site-packages\ptpython\repl.py", line 208, in embed7.8
    repl.start_repl(startup_paths=startup_paths)
  File "C:\Python27\lib\site-packages\ptpython\repl.py", line 51, in start_repl
    on_exit=AbortAction.RAISE_EXCEPTION)
  File "C:\Python27\lib\site-packages\prompt_toolkit\interface.py", line 290, in read_input
    next(g)
  File "C:\Python27\lib\site-packages\prompt_toolkit\interface.py", line 356, in _read_input
    loop_result = self.eventloop.loop()
  File "C:\Python27\lib\site-packages\prompt_toolkit\eventloop\win32.py", line 44, in loop
    keys = self._console_input_reader.read()
  File "C:\Python27\lib\site-packages\prompt_toolkit\terminal\win32_input.py", line 121, in read
    key_presses = self._event_to_key_presses(ev)
  File "C:\Python27\lib\site-packages\prompt_toolkit\terminal\win32_input.py", line 141, in _event_to_key_presses
    result = KeyPress(ev.AsciiChar.decode('ascii'), ev.AsciiChar.decode('ascii'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0x85 in position 0: ordinal
not in range(128)

```

I'm a windows with a french locale with Python 2.7. Remember, for your software to deal with non ascii characters : 
- use utf8 for all files;
- use "from __future__ import unicode_literals" for all files
- when you got an input, use your_input.decode(input_encoding). User input, sql query, file reading, downloads are all inputs.
- when you got an ouput, use your_ouput.encode(output_encoding). Terminal printing, sqlquery, writting in a file, HTTP post are all outputs.

**Comment by jonathanslenders** [comment]
Thanks for reporting! (And the explanation!)

I have to improve Windows support indeed. If you are able to write a patch, that's much appreciated.
Otherwise, I will try to figure this out myself, because it really is important.

**Comment by amjith** [comment]
Hi Jonathan,

@darkig has been looking into this issue from the pgcli side (https://github.com/dbcli/pgcli/issues/171) and got as far as this: 

> Last time I tried looking into this, I got as far as [this](https://github.com/jonathanslenders/python-prompt-toolkit/blob/0b4a2424b1ed3cf4c4975492f34f37d53080ba0d/prompt_toolkit/terminal/win32_input.py#L114). It's calling ReadConsoleInputA, specically requesting an ascii character. According to [this](https://msdn.microsoft.com/en-us/library/windows/desktop/ms684961(v=vs.85).aspx) (linked in the comments there), it should be possible to replace that call with ReadConsoleInputW instead, but I got in over my head there with C types and gave up.

Thought it might help you narrow this down further.

**Comment by jonathanslenders** [comment]
Thanks @amjith and @darikg,

I hope to find some time this weekend to fix this issue. 
``ReadConsoleInputW`` could indeed be the answer.

Jonathan

**Comment by jonathanslenders** [comment]
I think this is fixed now: https://github.com/jonathanslenders/python-prompt-toolkit/commit/35045205fcdb5389d99ef83a716ffdb8e8b4ff03

Windows is weird. The output encoding is cp437 while the input encoding is cp1252. But it seems to work now. It doesn't handle all unicode characters (I think the windows console doesn't even support it), but ``é`` works fine for instance.

**Comment by jonathanslenders** [comment]
Hi all,

This should be fixed, so I'm closing it.
A new Pypi release has been done. Please reopen or create a new issue when this still occurs.

Jonathan
