### ISSUE TITLE
ptipython crashes on startup: AttributeError: 'InteractiveShellEmbed' object has no attribute 'prompt_manager'

### ISSUE THREAD

**Issue by lillian27** [jonathanslenders/ptpython#131]
New 2.7.10 virtualenv on OS X.  Installed ipython and ptpython with pip.  pip freeze says:

Pygments==2.1.3
appnope==0.1.0
backports.shutil-get-terminal-size==1.0.0
decorator==4.0.10
docopt==0.6.2
ipython==5.0.0
ipython-genutils==0.1.0
jedi==0.9.0
pathlib2==2.1.0
pexpect==4.2.0
pickleshare==0.7.3
prompt-toolkit==1.0.3
ptpython==0.34
ptyprocess==0.5.1
simplegeneric==0.8.1
six==1.10.0
traitlets==4.2.2
wcwidth==0.1.7
wsgiref==0.1.2

On startup (last frame of trace, ipython.pyc):

    168         self.ipython_shell = ipython_shell
    169
--> 170         self.all_prompt_styles['ipython'] = IPythonPrompt(ipython_shell.prompt_manager)
    171         self.prompt_style = 'ipython'
    172

AttributeError: 'InteractiveShellEmbed' object has no attribute 'prompt_manager'

ipython and ptpython seem to work as expected.

**Comment by jonathanslenders** [comment]
Hi @lillian27, this is because of a change in IPython. Can you please update to the latest version of ptpython and try again? I just did a new release. (Thanks for reminding me!)

**Comment by lillian27** [comment]
I thought it might be related to the ipython 5.0 release.  Installed the newest ptpython (0.35) and everything looks good now.  Thanks!

BTW congrats on prompt_toolkit being used in Project Jupyter!

**Comment by jonathanslenders** [comment]
Thanks! Good to hear that it works now.
I close the issue, but feel free to open it again, if you still have some problems.
