### ISSUE TITLE
pypy

### ISSUE THREAD

**Issue by Duality4Y** [jonathanslenders/ptpython#134]
would it be possible to use ptpython with pypy ?
cause that would be awesome ! :)

**Comment by jonathanslenders** [comment]
Yes this is certainly possible.

Do you know how to create a virtualenv? If so, create a virtualenv with pypy as interpreter. (Something like: ``mkvirtualenv --python=pypy``.) Then, when inside that virtualenv, install ptpython: ``pip install ptpython``. Then it should automatically use pypy.

**Comment by Duality4Y** [comment]
yes i do know how to use virtualenv, 
good point i'll try it out right away ! :)
