### ISSUE TITLE
Question: What limitation stops ptpython being an editor

### ISSUE THREAD

**Issue by MortalCatalyst** [jonathanslenders/ptpython#140]
Hi

Really like using Ptpython it works at just the right feature level making me quite productive. What limitation is there to a flag allowing ptpython to edit in file mode not REPL?

Having tried to get nice Emacs and Vim configs and never quite succeeding, Ptpython just nails it perfectly and seems perfect that I could switch between REPL and file edit. Not putting this on the project alone just sussing out its viability.

**Comment by jonathanslenders** [comment]
Hi @MortalCatalyst,

Interesting question! I think there is no limitation except time. Writing an editor really takes a lot of time.

But maybe you already noticed pyvim. It's a Vi clone, build in Python, using the same prompt_toolkit framework. It works pretty well, but there are still a few bugs and it lacks a *lot* of features compared to everything that Vim has to offer. https://github.com/jonathanslenders/pyvim

I guess that in the future, it will slowly keep improving, but honestly it will be really hard to ever be as good as Vim or Emacs are.

What I want however, is to have at least the basic functionality working. That is whatever we need for Python coding. And with a decent performance. :)
