### ISSUE TITLE
slime type of plugins doesn't work with ptpython

### ISSUE THREAD

**Issue by kecmen** [jonathanslenders/ptpython#144]
Hi,

I'm using tmux and vim together with python console. There are couple of plugins to vim that allows it to integrate with tmux:
https://github.com/jgdavey/tslime.vim
https://github.com/jpalardy/vim-slime
https://github.com/epeli/slimux

Basically what these plugin does is they allow to send selected text to other tmux window. This works fine when I have python source opened and I send the text (for example class definition code) to window in which python interpreter is running. But sending the same code to ptpyhon messes the indentation. The reason is that ptpython has (rather nice and useful) feature of 'autoindenting'. This is great for interactive work, but it's problematic in cases like this. Even stripping lines before sending them from vim doesn't work - in this case the indentation is removed so ptpython threats every new method definition as being defined within the previous one.

Examples:
The code itself:
```
class A:
    def a(self):
        print('a')
    def b(self):
        print('b')
    def c(self):
        print('c')
```

without stripping the starting whitespaces:
```
>>> class A:
  2         def a(self):
  3                     print('a')
  4                         def b(self):
  5                                     print('b')
  6                                         def c(self):
  7                                                     print('c')
  8
 
```
with starting whitespaces removed - ptpython treats each new function as being part of the previous one:
```
>>> class A:
  2     def a(self):
  3         print('a')
  4         def b(self):
  5             print('b')
  6             def c(self):
  7                 print('c')
```

This can be handled by setting
`repl.paste_mode = True` in ~/.ptpython/config.py but then the interactive shell lost the ability to indent. Is there any possible way to treat this (like IPython?)

Thanks

**Comment by jonathanslenders** [comment]
Hi @kecmen,

Thanks for reporting this issue.

This is however a bug in any of those tools.
Those plugins should implement "bracketed paste". This is what most terminals do, and this would allows us to recognise pasted text. (I did not look into the source code of any of these tools, but it should be possible to make them send those escape sequences.)

Jonathan

**Comment by kecmen** [comment]
Hi,

You're right, I didn't know about that. Adding proper "brackeded paste" symbols in .vimrc fixed this.
Thank you

**Comment by jonathanslenders** [comment]
Good to know that it worked! :-)

**Comment by ddxv** [comment]
@kecmen Is it possible for you to share how you were able to fix this in your .vimrc?

I have checked: https://cirw.in/blog/bracketed-paste

And see that I need to use:
```
Enable bracketed paste: printf "\e[?2004h"
Wait for paste to start: you'll see \e[200~ on STDIN.
Wait for paste to stop: you'll see \e[201~ on STDIN.
Disable bracketed paste: printf "\e[?2004l"
```

I tried to see how the plugin vim-bracketed-paste works, but it seems it is for pasting into vim. Any help or hints you could give would be greatly appreciated.  Thanks!

**Comment by kecmen** [comment]
Hi,

i fixed it 'maually'. Adding relevant parts from config.py and .vimrc:

this is what's in my config.py for ptpython:
```
# Paste mode. (When True, don't insert whitespace after new line.)
repl.paste_mode = False
```

and this is how I send the code from vim to ptpython console in other tmux window( .vimrc)
```
nmap <C-y><C-y> :call <SID>Tslime(1)<CR>
imap <C-y><C-y> <ESC>:call <SID>Tslime(2)<CR>
vmap <C-y><C-y> :call <SID>Tslime(3, 1)<CR>

```
relevant parts of Tslime function
```
function! s:Tslime(mode, ...) range
    if b:filetype == 'python' || b:filetype == 'python3'
        " normal or insert mode
        if a:mode == 1 || a:mode == 2
            let l:line = GetLeftTrimmedCurrentLine()
            call SendToTmux(l:line . "\n")
        " visual mode
        elseif a:mode == 3

            let l:to_send = TrimSelectedLinesForPython()

            if a:1 == 1
                let l:to_send = MakeBracketedText(l:to_send)
            endif

            call SendToTmux(l:to_send . "\n")
....

where:
function! TrimSelectedLinesForPython()
    " if multiple lines are selected, fix the indentation
    if getpos("'<")[1] != getpos("'>")[1]
        let l:selected_lines = GetSelectedLines()
        " fix the indentation - if the selected lines are indented, left
        " trimmed them
        let l:trimmed_selected_text = ""
        " number of spaces in first line, that creates the indentation
        let l:spaces_indent = matchstr(l:selected_lines[0], "^\\s*")

        for l:line in l:selected_lines
            if match(l:line, "^\\s*$") == 0
                let l:line = "    "
            else
                let l:line = substitute(l:line, "^" . l:spaces_indent, "", "g")
            endif
            let l:trimmed_selected_text = l:trimmed_selected_text . l:line . "\n"
        endfor
    " if only a part of single line is selected, don't mess with the indentation
    else
        let l:trimmed_selected_text = GetSelectedText()
    endif

    return l:trimmed_selected_text
endfunction

function! MakeBracketedText(text)
    " https://cirw.in/blog/bracketed-paste
    " https://github.com/ConradIrwin/vim-bracketed-paste/blob/master/plugin/bracketed-paste.vim
    let l:bracketed_paste_start = "[200~"
    let l:bracketed_paste_end = "[201~"

    return (l:bracketed_paste_start . a:text . l:bracketed_paste_end)
endfunc

```
those bracketed_paste_start and end variables are (in case the content is mangled):
0x1B 0x5B 0x32 0x30 0x30 0x7E
0x1B 0x5B 0x32 0x30 0x31 0x7E

Also, I'm using this plugin for vim:
Plugin 'https://github.com/jgdavey/tslime.vim'

**Comment by blayz3r** [comment]
Windows does not support bracketed paste yet, is there a way of sending
```python
 python_input.paste_mode = not python_input.paste_mode
```
or **"F6"**

Currently you can send command like quit() and they work
