### ISSUE TITLE
Wrong python version with python wheels

### ISSUE THREAD

**Issue by jnth** [jonathanslenders/ptpython#146]
Hi all,

After installing `ptpython` with `pip install ptpython`, I found wrong python version in executable names:

Here's an example with a Python 3.4 virtual environment:
```
-rwxrwxr-x 1 jv jv  243 nov.   2 07:29 easy_install
-rwxrwxr-x 1 jv jv  243 nov.   2 07:29 easy_install-3.4
-rwxrwxr-x 1 jv jv  215 nov.   2 07:29 pip
-rwxrwxr-x 1 jv jv  215 nov.   2 07:29 pip3
-rwxrwxr-x 1 jv jv  215 nov.   2 07:29 pip3.4
-rwxrwxr-x 1 jv jv  245 nov.   2 07:29 ptipython
-rwxrwxr-x 1 jv jv  245 nov.   2 07:29 ptipython3
-rwxrwxr-x 1 jv jv  245 nov.   2 07:29 ptipython3.5
-rwxrwxr-x 1 jv jv  244 nov.   2 07:29 ptpython
-rwxrwxr-x 1 jv jv  244 nov.   2 07:29 ptpython3
-rwxrwxr-x 1 jv jv  244 nov.   2 07:29 ptpython3.5
lrwxrwxrwx 1 jv jv    7 nov.   2 07:29 python -> python3
-rwxrwxr-x 1 jv jv 3,6M nov.   2 07:29 python3
lrwxrwxrwx 1 jv jv    7 nov.   2 07:29 python3.4 -> python3
-rwxrwxr-x 1 jv jv 2,3K nov.   2 07:29 python-config
-rwxrwxr-x 1 jv jv  222 nov.   2 07:29 wheel
```

After digging why this issue occur, I found that the wheel version in PyPi (`ptpython-0.36-py3-none-any.whl`) contains this entry point:

```
[console_scripts]
ptipython = ptpython.entry_points.run_ptipython:run
ptipython3 = ptpython.entry_points.run_ptipython:run
ptipython3.5 = ptpython.entry_points.run_ptipython:run
ptpython = ptpython.entry_points.run_ptpython:run
ptpython3 = ptpython.entry_points.run_ptpython:run
ptpython3.5 = ptpython.entry_points.run_ptpython:run
```

I can suggest you:
  - to be less specific (remove the minor version in executable names: `ptipython3.5` and `ptpython3.5`)
  - or to build specific wheels with:
    - `python3.4 setup.py bdist_wheel --python-tag py34`
    - `python3.5 setup.py bdist_wheel --python-tag py35`
    - `python3.6 setup.py bdist_wheel --python-tag py36`.
    - ...

I can help to open a PR in the first case or upload wheel to PyPi.

**Comment by jonathanslenders** [comment]
This makes sense. I see what's going on.
On my system, I have several virtualenvs, some with Python 3.4, other with 3.5 and even 3.6 and I didn't consistently use the same environment to build the wheel. I also did not realise that this would be executed while building the wheel.
Personally, I really prefer to have only one wheel for Python 3. Any PR to fix this is welcome.

@zlsun What do you think?

**Comment by zlsun** [comment]
@jonathanslenders , I also prefer the first solution (remove the minor version in executable names).

**Comment by jnth** [comment]
I send you a PR to remove two lines in `setup.py`.
Tested in local and everything is fine.

**Comment by jonathanslenders** [comment]
Merged in: https://github.com/jonathanslenders/ptpython/commit/16e4e3155733ad8c90312414cc975315ad8566d3
Thanks everyone!
