### ISSUE TITLE
input/getpass not working in ptpython

### ISSUE THREAD

**Issue by Red5d** [jonathanslenders/ptpython#147]
Tested in python 2.6, 2.7, and 3.5.

The input(), raw_input(), and getpass.getpass() functions don't work properly in ptpython. When pressing "enter" after typing in text at the prompt from these functions, "^M" characters appear (when using input/raw_input) and the prompt doesn't return.

**Comment by jonathanslenders** [comment]
Hi @Red5d,

Thanks, I can reproduce this. I think this is coming from a recent change in prompt_toolkit. I'm investigating it right now.

**Comment by jonathanslenders** [comment]
Fixed in: https://github.com/jonathanslenders/python-prompt-toolkit/commit/9b6cd5adfc6892e0bf9251366e03041a45885430

**Comment by jonathanslenders** [comment]
A new prompt_toolkit release has been pushed. Can you please test it?
I'm closing this issue as well. Feel free to reopen it in case you notice any issues.
