### ISSUE TITLE
Cannot patch __main__.open

### ISSUE THREAD

**Issue by butla** [jonathanslenders/ptpython#148]
This is a strange behavior that I've noticed while running some [sample from Python documentation](https://docs.python.org/3/library/unittest.mock.html#mock-open). Patching doesn't fail, but it doesn't really succeed, as a real file gets saved. Does ptpython do some magic with `__main__`?

Anyway, below is the terminal session explaining the issue:
```
butla@b2:~$ python3
Python 3.5.2 (default, Sep 10 2016, 08:21:44)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from unittest.mock import patch, mock_open
>>> m = mock_open()
>>> with patch('__main__.open', m):
...     with open('foo', 'w') as h:
...         h.write('some stuff')
...
>>> m.mock_calls
[call('foo', 'w'),
 call().__enter__(),
 call().write('some stuff'),
 call().__exit__(None, None, None)]
>>>
butla@b2:~$ # works fine with the regular interpreter
butla@b2:~$ 
butla@b2:~$ ptpython
>>> import sys

>>> sys.version
'3.5.2 (default, Sep 10 2016, 08:21:44) \n[GCC 5.4.0 20160609]'

>>> from unittest.mock import patch, mock_open

>>> m = mock_open()

>>> with patch('__main__.open', m):
  2     with open('foo', 'w') as h:
  3         h.write('some stuff')

>>> print(m.mock_calls)
[]
```

Version: 0.36
OS: Kubuntu 16.04

**Comment by facingBackwards** [comment]
@butla, any chance you could test your use case against #202?

**Comment by butla** [comment]
@facingBackwards Yep, it works, you've fixed it :)

**Comment by jonathanslenders** [comment]
Thanks everyone! I merged the fix. I hope to push a new release somewhere next week.

**Comment by butla** [comment]
@jonathanslenders Ok, so if this is merged, then I'm closing this issue.
