### ISSUE TITLE
IPython+Ubuntu won't autocomplete on %run

### ISSUE THREAD

**Issue by ianozsvald** [jonathanslenders/ptpython#15]
Hello, I've just seen your rather awesome library. Some of it works great, a common feature that I use ("%run <somechar><tab to complete on a local filename>") doesn't work. Maybe I'm missing something?

I'm on Ubuntu (Linux Mint 17.1 based on Ubuntu 14.04), using Python 3.4.2 (via Anaconda) with ptpython 0.4 (installed using pip today) and IPython 2.2.0. I'm using a default Ubuntu terminal.

If I type:
$ ptipython
...
In [1]: open("i<cursor is here>
                insert_pickle_into_elasticsearch.py  File <- really neat autocompletion!
but if I try:
In [1]: %run i <- nothing happens, no autocompleteion
and if I continue to type the filename (e.g. "%run insert_") and try tab, nothing happens and there are no options. Does Jedi know about %run filename completion?

If I use the exclamation-mark shell convention:
In [1]: !autopep8 -i insert_
to run a shell command outside of IPython, tab completion fails here too (but if I type the full filename, autopep8 works as expected). 

Both the above examples work with tab completion inside a normal IPython shell.

Sidenote - I'm not sure how the keybindings work on other platforms but if I use Ctrl-Shift-N (as noted in your README "Tab and shift+tab complete the input. In Vi-mode, you can also use Ctrl+N and Ctrl+P.") then I get a new Ubuntu Terminal (!). 

I'll keep tabs on this, it looks most promising!

**Comment by jonathanslenders** [comment]
Thanks for the complements.
The reason that %run does not autocomplete is simply because it hasn't been implemented yet.
It's doable though. The hard part is to now which magic commands expect a filename as argument and which don't. The reason that "open('i" autocompletes is because we simply have autocompletion on filenames inside string literals. We can of course hard-code that %run needs to be followed by a filename, but maybe there are others.

About Ctrl+N: it is possible that your terminal application catches this shortcut before it even reaches ptpython. Most terminal applications (gnome-terminal in your case) have the option to configure shortcuts. These are captured and not send to the application running inside the terminal.
So, either you remove the default Ctrl-N binding in gnome-terminal, or you use Tab. I'm also thinking on having key bindings for ptpython configurable, but that will be a real challenge.

**Comment by ianozsvald** [comment]
Hey there. For me %run is an everyday part of my IPython use. I'm a data scientist, building throw-away scripts and prototyping them at the cmd line (or building them up using GVim) is my normal mode. 

If %run were to work with tab-completion then I'd probably switch to ptipython daily, having auto-complete via jedi (which I already have in vim) is rather lovely. I can't offer dev time (sorry!) and I appreciate you've got plenty to do but take this a strong +1 from me for %run support (and whilst a hacky solution is hacky, I wonder how many other folk use %run as their 90%-of-the-time magic?).

Re. Ctrl-N - figured as much. Keybindings across platforms are only every tricky! That's not a deal-breaker for me, just an observation maybe to add to the README if it trips others too.

I'll aim to mention ptipython at my next PyDataLondon meetup, it should bring you a bunch of curious new IPython users.

**Comment by jonathanslenders** [comment]
Thanks for the explanation. I try to make priority of the %run-autocompletion.

**Comment by jonathanslenders** [comment]
Hi @ianozsvald 

I just implemented autocompletion for %run and did the same for 16 other IPython commands. It wasn't really hard to do. See this commit: https://github.com/jonathanslenders/ptpython/commit/8663d02eab164093e0f03ccd9a16283a0696b9ab#diff-690303871df694cf38fa5735d9c843beR64

One question. Are you willing to try it before I push a new version to Pypi. I need you to clone this repository. Run ``python setup.py install`` and start ``ptipython`` again. Tell me whether it works for you. Then I can release a new version to Pypi.

Also, if you use some other IPython magics that need autocompletion, but don't have it yet. Please tell me.

Thanks for willing to mention ptipython at PyDataLondon, I really appreciate that, and I hope you are able to do it.

Cheers!
Jonathan

**Comment by ianozsvald** [comment]
I've been using <master> for an hour, this is clear improvement, cheers! This introduces some other edge cases but (for me at least) this is now usable, so I'll try it all today and report anything else I come across.

Specifically:
"%run <dir/script>" works with tab-completion :-)
"%cd <somedir>" tab-completes as expected

"%run <dir/script> <second arg e.g. input file to script>" doesn't tab-complete on the second argument (but IPython does)
"cd <somedir>" generates a syntax error, this works in IPython (cd is a shortcut to %cd in IPython)

Re. pydatalondon - sure, approximately 100 people should see it and I sent it out on my twitter account (@ianozsvald) last night

**Comment by jonathanslenders** [comment]
Thanks for the feedback! I appreciate it.

About "cd <somedir>", that's a tricky one, because the grammar is a bit ambigue. "cd" could also be a Python variable. But I have solved a similar problem some time ago for "ptpdb". It is fun. :)

**Comment by jonathanslenders** [comment]
Hi @ianozsvald,

Closing this one. I think all auto completions that you asked for were implemented.
Please create a new issue in case you still find some bugs.

Jonathan
