### ISSUE TITLE
Allow Ctrl-d as exit confirmation

### ISSUE THREAD

**Issue by ulope** [jonathanslenders/ptpython#159]
It would be very nice if `Ctrl-d` could be used as an alternative confirmation for the "Do you really want to exit" dialog. IPython handles it the same way.

**Comment by jonathanslenders** [comment]
Hi @ulope,

Thanks for the suggestion! Implemented in: https://github.com/jonathanslenders/ptpython/commit/9fb61ac930904d242ef194e5f32632bb74de19e7

**Comment by ulope** [comment]
Wow, lightning fast response. I wish I were as responsive in my open source projects. Thanks!

**Comment by jonathanslenders** [comment]
You're welcome!

**Comment by jonathanslenders** [comment]
(Note that the latest master commit of ptpython requires also the latest master of prompt_toolkit. One backwards-incompatible change was made last week.)
