### ISSUE TITLE
Problem with "v" key

### ISSUE THREAD

**Issue by ingvast** [jonathanslenders/ptpython#170]
My installation with ptpython has a problem with the "v" key.  Pressing it throws me directly to the nano editor.
It happens in vi Insert mode as well as in emacs mode.
Is there something with keymappings gone wrong?
Any hint is welcome.

Apart from this "little" problem I really like the repl interface. Great programming.
/johan

**Comment by jonathanslenders** [comment]
Hi @ingvast,
This is something bad that happened during the last prompt_toolkit release a few days ago.
I just fixed it in this commit: https://github.com/jonathanslenders/python-prompt-toolkit/commit/5bab814dc0c0a0cf4a1a8acfb0fbb17d37db96a7
A new prompt_toolkit release has been pushed.
Can you try to run ``pip install -U prompt_toolkit`` and see whether it works again?

Thanks a lot!
Jonathan

**Comment by ingvast** [comment]
Excellent, the upgrade of prompt_toolkit fixed it. 
Thanks a lot for quick response.
/johan
