### ISSUE TITLE
No attribute suggestion for pandas objects on Python 3.6

### ISSUE THREAD

**Issue by shaypal5** [jonathanslenders/ptpython#175]
Hey there, 😃 

I just upgraded my python today from 3.5 to 3.6.

I reinstalled my whole python installation in my 'conda' virtual environment from scratch, and as a result I have, at the moment, fresh installation of Python 3.6.0, iPython, ptpython, jedi and so forth.

Anyway, as a result of the upgrade, the attribute windows that would pop up as I would write a dot after a variable holding a pandas.DataFrame or pandas.Series object no longer pops up. 

Specifically for pandas.Series the following error prints:
_"is_time_series is deprecated. Please use Series.index.is_all_dates"_

The source of this message can be found in line 284 of the following `pandas` source file:
[https://github.com/pandas-dev/pandas/blob/master/pandas/core/series.py](https://github.com/pandas-dev/pandas/blob/master/pandas/core/series.py)

This does not happen for the same attribute-pop-up scenario in iPython or Jupyter Notebook; it works fine in both cases.

It happened with both `jedi 0.9` and `jedi 0.10`

Attached below is a print-screen of the phenomenon:
![image](https://cloud.githubusercontent.com/assets/917954/23218869/1a7bf27e-f926-11e6-956a-28da775cb1e2.png)

Cheers,
Shay

**Comment by jonathanslenders** [comment]
Hi @shaypal5,

Thanks for reporting! This looks like either a Pandas or Jedi issue. Either Jedi is executing some code while generating the completions. Or Pandas has code that contains side effects in some ``__dir__`` or ``__getattr__`` functions. Generating completions should in any case not execute something, but that's what happens.

Jonathan

**Comment by shaypal5** [comment]
Oh, well. Thanks! :)
