### ISSUE TITLE
[question] Indention on output when embedded from different curses app

### ISSUE THREAD

**Issue by cthrax** [jonathanslenders/ptpython#179]
Hi,

You may not be able to help me, but this is my first foray into curses and I've got an app that I'm able to open ptpython in (and subsequently close, very useful!), but all the output from ptpython behaves as if bracketed paste mode was required (indenting every new line more). Do you know of a setting that would help with this? It'd be awesome to run some setting before calling embed, then revert it after so my original curses app behaves as expected.

Thanks in advance!

**Comment by jonathanslenders** [comment]
Hi @cthrax, did you check this link: https://cirw.in/blog/bracketed-paste ?
```
Enable bracketed paste: printf "\e[?2004h"
Wait for paste to start: you'll see \e[200~ on STDIN.
Wait for paste to stop: you'll see \e[201~ on STDIN.
Disable bracketed paste: printf "\e[?2004l"
```

**Comment by cthrax** [comment]
Hi @jonathanslenders , thanks for the quick response! I did find and try that, to no avail. I'm convinced that I'm running into the bracketed paste problem, it just seems to behave the same. I haven't quite dug deep enough to figure out how ptpython displays values, but initial guess has been that there is a curses setting, that's global, and my app is tromping on that setting, but not knowing how ptpython writes the screen, I didn't know how likely that was.

Feel free to tell me this is not a ptpython problem, and I need to go elsewhere, but I thought I would start here.

Thanks again!

**Comment by cthrax** [comment]
@jonathanslenders thanks for the help, I found out I needed to call "curses.reset_shell_mode()" before starting ptpython. This fixed all my issues and really had nothing to do with ptpython.
