### ISSUE TITLE
command-history-matcher in ptipython no longers works as per ipython

### ISSUE THREAD

**Issue by ianozsvald** [jonathanslenders/ptpython#18]
The command-history-matcher (is there a better name?) in IPython lets you do the following:
```
In[1]: %run <somescript>
In[2]> %ru<hit-up-arrow>  
```
and then it'll cycle through previous commands in In that match with "%ru", so you can quickly jump back to an earlier command

This works in IPython but doesn't work in pyipython, the ptipython behaviour is to cycle through Jedi "%ru" autocomplete commands, rather than to cycle through the command history.

Jedi has control here so the old behaviour has presumably been cut out. Possibly one approach is to let the user hit a key like Esc to stop using Jedi, then to fall back on the previous arrow-up, arrow-down behaviour?

Based on my usage patterns I'd say this is not a deal breaker (as I can still start with an empty input line and just hit arrow-up a few times)

Workaround: "<ctrl-r>ru" uses the incremental-backwards-search just as it would in IPython to find a previous command.

**Comment by jonathanslenders** [comment]
You're probably the third or fourth asking for this:
https://github.com/jonathanslenders/python-prompt-toolkit/issues/36

It's a readline option. I believe it's configurable for GNU readline.
I still have to figure out how to handle this in a multiline environment, but it should be doable.

Feel free to create other issues for everything you are missing.

**Comment by jonathanslenders** [comment]
Hi @ianozsvald,

This has been implemented. Have a look at this setting: https://github.com/jonathanslenders/ptpython/blob/master/examples/ptpython_config/config.py#L53
You can also enable it from the options menu.

Let me know whether it works.
Jonathan
