### ISSUE TITLE
Scrolling up the terminal during the session.

### ISSUE THREAD

**Issue by abhi18av** [jonathanslenders/ptpython#184]
Hi @jonathanslenders ,

This is an amazing piece of work!! Thanks :smile: 

However, I feel that the ability to scroll up/down the terminal during a session would be a real add-on to the repl. In case, I've overlooked some such setting already could you please let me know? I'm still somewhat of a beginner with terminal programs

**Comment by jonathanslenders** [comment]
Hi @abhi18av,

Do you mean that you'd like to have a key binding to control the scroll bar of the terminal?
This is nothing that prompt_toolkit is able to control. Terminals can implement key bindings for this (very ofter Shift+PageUp/Down). But this is nothing that we can control.

Jonathan

**Comment by whwkong** [comment]
@abhi18av 
See issue #121 
I had the same problem as well; I use iTerm2.  Issue was resolved by holding down OPT while scrolling.

Hope this helps.

@jonathanslenders Agree with @abhi18av  Amazing piece of work!

**Comment by whwkong** [comment]
In `~/.ptpython.config.py`:

```
from __future__ import unicode_literals
from prompt_toolkit.keys import Keys


__all__ = (
    'configure',
)


def configure(repl):
    """
    Configuration method. This is called during the start-up of ptpython.
    :param repl: `PythonRepl` instance.
    """
    repl.enable_mouse_support = True
```

Change `repl.enable_mouse_support = False`  

Now scrolling works without holding down OPT key.

**Comment by abhi18av** [comment]
Whoops, forgot to close this a long time back :)

Sorry everyone..

**Comment by itsayellow** [comment]
On a macOS Terminal, I couldn't get mouse scrolling to work at all, with or without any modifier key.  The workaround of disabling mouse support works, though.

**Comment by plutonium-239** [comment]
same here, i guess it has been broken for more than 4 years now?
