### ISSUE TITLE
ptpython over socket?

### ISSUE THREAD

**Issue by traverseda** [jonathanslenders/ptpython#190]
I'd like to run ptpython over a websocket, but it seems pretty tied to stdout/stdin. How would I go about capturing the IO for a ptpython console and sending/receiving from a custom data source?

I've tried something like `sys.stdout=FakeStdOut(webSocket)`, and that doesn't seem to work.

**Comment by jonathanslenders** [comment]
Hi @traverseda,

Have a look at this example: https://github.com/jonathanslenders/ptpython/blob/master/examples/asyncio-ssh-python-embed.py

It is possible, but not obvious. Hopefully, that helps.
