### ISSUE TITLE
Cannot use z.i with ptpython

### ISSUE THREAD

**Issue by Julian** [jonathanslenders/ptpython#200]
I haven't looked at the code yet, but ptpython is executing code differently than a regular interpreter would.

After `pip install zope.interface`

```
import zope.interface

class I(zope.interface.Interface):
    pass
```

works fine in a regular REPL, but in ptpython produces:

```
>>> class I(zope.interface.Interface):
...     pass
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/julian/.local/share/virtualenvs/dev/site-packages/zope/interface/interface.py", line 369, in __init__
    raise InvalidInterface("Concrete attribute, " + name)
InvalidInterface: Concrete attribute, __module__
Concrete attribute, __module__
```

**Comment by jonathanslenders** [comment]
Is it possible that this would be fixed by: https://github.com/jonathanslenders/ptpython/issues/148 ?

**Comment by Julian** [comment]
@jonathanslenders it looks like that's already been merged -- I just gave this a shot on current master though, and it still seems to fail in the same way.

**Comment by facingBackwards** [comment]
@Julian Could you have a look at #203 ? It's part of the fix for #148 that I missed in my fix in #202.

**Comment by Julian** [comment]
@facingBackwards can confirm that makes the code in the issue here work too, thanks!

**Comment by jonathanslenders** [comment]
Hi @Julian, ptpython 0.40 has been released. Can you check whether it works now?

**Comment by Julian** [comment]
Looks great, thanks!
