### ISSUE TITLE
Confirmation on exit

### ISSUE THREAD

**Issue by sshin718** [jonathanslenders/ptpython#22]
Hi, I am wondering why `ptpython` doesn't ask confirm to exit.

As you know, Ctrl+D is used for backspace on some platforms.
So, when using `ptpython`, I often hit Ctrl+D by mistake and `ptpython` exits unintentionally.

I wrote some code to prevent this as `ipython` does.
Does someone agree with me?

**Comment by congee** [comment]
same issue, no matter vi mode or emacs mode.

**Comment by jonathanslenders** [comment]
Hi all, thanks for reporting this issue! I will keep this in mind and I'll try to make the bahaviour configurable. (Currently I'm very busy with other things, but I hope to resume ptpython development during the next week.)

**Comment by jonathanslenders** [comment]
@sshin718 What platforms are you actually talking about?
Is it a readline option?

**Comment by sshin718** [comment]
@jonathanslenders Thank you for your reply.
Sorry I meant 'delete to the right of cusor', not backspace. And, about platforms you can look into here. https://en.wikipedia.org/wiki/Table_of_keyboard_shortcuts
I'm using fedora and mac os.

**Comment by donkopotamus** [comment]
@jonathanslenders `Control-D` is a standard `readline` key chord ... ([documentation](http://cnswww.cns.cwru.edu/php/chet/readline/readline.html#SEC4)).  Its also used in emacs and on linux both bash and python (via readline) use the convention that `Control-D` on an empty line closes the session whereas on a non-empty line it deletes the character under the cursor.  Unfortunately as an old dog who cannot lose new tricks its almost reflexive to use for deletion and I find I keep killing a tab!

**Comment by jonathanslenders** [comment]
Thanks for pointing this out @donkopotamus  I will fix it.

**Comment by jonathanslenders** [comment]
Hi all, ``Control-D`` now deletes the character under the cursor.: https://github.com/jonathanslenders/ptpython/commit/52d5765cec8d78665ccee27c11e25a36594c94fa

One other question. Is anybody actually using the tab pages of ptpython? I'm thinking about removing this functionality. (Personally I don't find much use for it, and I prefer to keep the code base clean and maybe this can be build as an extension.)

Second thing. One of the priorities is to have custom configurations. I'm taking my time for this, because I want to do it right, rather than rushing into it. But once finished, everyone should be able to define their own key bindings.

**Comment by donkopotamus** [comment]
I've only just started used `ptpython` so take my views with a grain of salt.  

The current design of tabs, where each tab shares the same environment, limits its usage I think.  Almost the only time you would want another tab is when you are in the middle of a complex expression and realise you need to do something else first.  Then using tabs feels like an odd solution to the problem ... a more natural solution (especially to an experienced console/terminal user) would be to have some way to temporary "kill" (cut) the expression to a clipboard ... then you do whatever you wanted to do and then "yank" (paste) it back.

If each tab had a different namespace/environment they might be more useful but I think there are plenty of other ways for people to solve the problem of wanting multiple interpreters - tabbed terminal windows, tmux/screen etc.

**Comment by jonathanslenders** [comment]
@donkopotamus I agree. I removed the tabs like they were implemented.
Thanks for the feedback! I appreciate it.

**Comment by Shchvova** [comment]
how to disable this cursed feature?
