### ISSUE TITLE
2.0 branch text-editor.py example has undefined search_field in do_find

### ISSUE THREAD

**Issue by meeas** [jonathanslenders/ptpython#236]
File "text-editor.py", line 245, in do_find
    get_app().layout.focus(search_field)

Exception name 'search_field' is not defined

Haven't played with the library enough to spot the problem as it seems like it is defined on line 53 in the call to TextArea.

**Comment by jonathanslenders** [comment]
I believe this has been fixed. If not, could you reopen this issue in the prompt_toolkit repository?
