### ISSUE TITLE
User Configuration

### ISSUE THREAD

**Issue by douglarek** [jonathanslenders/ptpython#24]
I makes `Completion menu` into toolbar, but when I close session, It turns back to the original.

Maybe It should be user-configurable.

**Comment by jonathanslenders** [comment]
Yes. I know about this. We don't remember configurations yet. It's on my todo list. Hopefully it's for any time soon. :)
The same for vi/emacs mode, visibility of signatures, docstrings, etc..

**Comment by douglarek** [comment]
@jonathanslenders Thanks, very cool !
