### ISSUE TITLE
Proposal: Pin `jedi>=0.9.0,<=0.10.2'` due to regression in `0.11.0`

### ISSUE THREAD

**Issue by myii** [jonathanslenders/ptpython#242]
#### Proposal

https://github.com/jonathanslenders/ptpython/blob/da2c5281f60c2d8a92749709219771ffaa84220f/setup.py#L24

Change this to either:

* `jedi>=0.9.0,<=0.10.2',`
* `'jedi>=0.9.0,<0.11.0',`

This resolves the issues explained below.

Also resolves #229.

#### Description of problems

Encountered a crash when typing the period of `Revision.`, a [django-reversion](https://github.com/etianen/django-reversion) model:

```python-traceback
In [1]: Revision.Exception in thread Thread-429:
Traceback (most recent call last):
  File ".../.pyenv/versions/Django_v2.0.x/lib/python3.6/site-packages/jedi/cache.py", line 46, in wrapper
    return getattr(self, name)
AttributeError: 'MixedName' object has no attribute '_infer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../.pyenv/versions/Django_v2.0.x/lib/python3.6/site-packages/jedi/evaluate/compiled/access.py", line 120, in wrapper
    cache[key]
KeyError: 140232415539440

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../.pyenv/versions/3.6.4/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File ".../.pyenv/versions/3.6.4/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File ".../.pyenv/versions/Django_v2.0.x/lib/python3.6/site-packages/prompt_toolkit/interface.py", line 865, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File ".../.pyenv/versions/Django_v2.0.x/lib/python3.6/site-packages/prompt_toolkit/contrib/regular_languages/completion.py", line 37, in get_completions
    self._get_completions_for_match(m, complete_event))
  File ".../.pyenv/versions/Django_v2.0.x/lib/python3.6/site-packages/prompt_toolkit/contrib/regular_languages/completion.py", line 81, in _remove_duplicates
    for i in items:
  File ".../.pyenv/versions/Django_v2.0.x/lib/python3.6/site-packages/prompt_toolkit/contrib/regular_languages/completion.py", line 64, in _get_completions_for_match
    for completion in completer.get_completions(document, complete_event):
  File ".../.pyenv/versions/Django_v2.0.x/lib/python3.6/site-packages/ptpython/completer.py", line 127, in get_completions
    completions = script.completions()
  File ".../.pyenv/versions/Django_v2.0.x/lib/python3.6/site-packages/jedi/api/__init__.py", line 174, in completions
    completions = completion.completions()
  File ".../.pyenv/versions/Django_v2.0.x/lib/python3.6/site-packages/jedi/api/completion.py", line 102, in completions
    return sorted(completions, key=lambda x: (x.name.startswith('__'),
  File ".../.pyenv/versions/Django_v2.0.x/lib/python3.6/site-packages/jedi/api/completion.py", line 43, in filter_names
    k = (new.name, new.complete)  # key
  File ".../.pyenv/versions/Django_v2.0.x/lib/python3.6/site-packages/jedi/api/classes.py", line 436, in complete
    return self._complete(True)
  File ".../.pyenv/versions/Django_v2.0.x/lib/python3.6/site-packages/jedi/api/classes.py", line 406, in _complete
    if self._name.api_type == 'param' and self._stack is not None:
  File ".../.pyenv/versions/Django_v2.0.x/lib/python3.6/site-packages/jedi/evaluate/compiled/mixed.py", line 90, in api_type
    return next(iter(self.infer())).api_type
  File ".../.pyenv/versions/Django_v2.0.x/lib/python3.6/site-packages/jedi/cache.py", line 48, in wrapper
    result = func(self)
  File ".../.pyenv/versions/Django_v2.0.x/lib/python3.6/site-packages/jedi/evaluate/compiled/mixed.py", line 85, in infer
    _create(self._evaluator, access_handle, parent_context=self.parent_context)
  File ".../.pyenv/versions/Django_v2.0.x/lib/python3.6/site-packages/jedi/evaluate/compiled/access.py", line 125, in wrapper
    result = func(evaluator, obj, parent_context)
  File ".../.pyenv/versions/Django_v2.0.x/lib/python3.6/site-packages/jedi/evaluate/compiled/mixed.py", line 205, in _create
    result = _find_syntax_node_name(evaluator, access_handle)
  File ".../.pyenv/versions/Django_v2.0.x/lib/python3.6/site-packages/jedi/evaluate/compiled/mixed.py", line 197, in _find_syntax_node_name
    return module_node, names[-1].parent, path, code_lines
IndexError: list index out of range
```

* While looking for a solution, found issue #229 with a similar traceback

After restarting `shell_plus`, found further problems with both autocomplete and the documentation popup while typing `User.objects.get(pk=1)`:

* Autocomplete problem
    * Autocomplete is displayed after `User.`
    * But not working after `User.objects.`
* Documentation popup
    * Not displayed at `User.objects.get(`

#### Solution: Downgrading `jedi` to `0.10.2`

It was obvious that this must have been working at some point in history, so worked through the [release history](https://pypi.org/project/jedi/#history) installing previous versions of `jedi`.  Once I got to `0.10.2`, **everything mentioned above** started working properly.

**Comment by davidhalter** [comment]
Dude, 0.10.2 is just really old and has probably 30 more bugs than 0.12.0. If you find a bug then report it like you did and that's probably good enough, it will get fixed eventually.

**Comment by myii** [comment]
@davidhalter Thanks for your response.

http://django-extensions.readthedocs.io/en/latest/shell_plus.html

> The default resolution order is: `ptpython`, `bpython`, `ipython`, `python`.

Unfortunately, this particular bug is a blocker; it renders `shell_plus` effectively unusable with `ptpython`.  Have to restart the shell each time there is a crash.

Since any version above `0.9.0` fulfils the requirement, then `0.10.2` is the best available workaround for the time being.

**Comment by jonathanslenders** [comment]
Hi all, I haven't had the time lately to look at these issues, but we should definitely upgrade to 0.12.0.
If anyone has a patch, I'll probably merge it. Otherwise I hope to do it myself in the coming weeks.

**Comment by myii** [comment]
@jonathanslenders That's good news.  Getting `0.12.0` working would be far more ideal.  Thanks.

**Comment by davidhalter** [comment]
So there's a chance that only you might be affected. It might be a blocker for you and not others. To mitigate this you can also change the resolution order in django extensions for a few months (until this bug might be fixed).

Not sure though if 0.12.0 fixes this one.

**Comment by myii** [comment]
@davidhalter @jonathanslenders

Firstly, just to be clear, `jedi==0.12.0` is automatically selected during the installation of `ptpython`.  Which is why I opened this discussion in the first place, to consider if this should be avoided.

In any case, I've got some far more interesting results to share with you.  *I've tracked down the commits where these regressions occur*.

---

#### Method of testing

@davidhalter above:

> So there's a chance that only you might be affected. It might be a blocker for you and not others.

* I've tracked down the regressions on my own machine
* However, I've then taken another machine with a recent installation of Ubuntu 18.04 beta and confirmed each of these regressions in fresh virtual environments
    * Python 3.6.5
    * Python 3.5.5

> To mitigate this you can also change the resolution order in django extensions for a few months (until this bug might be fixed).

* I've taken `shell_plus` out of the equation -- all of the following tests are using `ptpython` directly

---

#### Bugs tested

There are three bugs that have been tested.  `ptpython` is non-functional after the crashes and needs to be restarted:

1. [Non-crash] Autocomplete & Documentation popup not working
    * `User.objects.` -- No autocomplete after this point
    * `User.objects.get(` -- Documentation popup not displayed
1. [Crash] Issue #229
    * `import signal`
    * `signal.SIGALRM.` -- crash when the period is typed
1. [Crash] Described at the top of this issue
    * `Revision.` -- crash when the period is typed

---

#### Regression history

The following table shows the commit where each regression took place:

Version / Commit | Bug 1 | Bug 2 | Bug 3
-|-|-|-
v0.10.2 | - | - | -
https://github.com/davidhalter/jedi/commit/88cfb2cb91bed04de4b3760ab3d48893c2214f41 | Y | - | -
https://github.com/davidhalter/jedi/commit/9dd2027299fc4964ed5b77446fc04e3a70a0ec6e | Y | Y | -
v0.11.0 | Y | Y | -
v0.11.1 | Y | Y | -
https://github.com/davidhalter/jedi/commit/f9ec989835cc1decfb478bce92edc3cec4f992fb | Y | Y | Y
v0.12.0 | Y | Y | Y

---

#### Comments

1. @davidhalter Since the main discussion has been here, continued over here rather than at https://github.com/davidhalter/jedi/issues/1087
1. @Carreau Since you've shown an interest in this, thought I'd inform you of these findings

**Comment by davidhalter** [comment]
I fixed it. You can close (it's not released yet, though, will be in 0.12.1). Here you mention multiple bugs, I hope they are fixed, otherwise please open new issues in Jedi.

@myii Thanks for the research, but if you just invested all of that time into fixing the bug you would have probably fixed the issue (it's a +-3 line fix). If you compare versions you always have to check how much changed in between. The diff to 0.10.2 is `11114 insertions(+), 13304 deletions(-)`. This is an extreme amount of changes considering that Jedi's code is smaller than 30kLOC.

**Comment by myii** [comment]
So Bug 1 [isn't really a bug](https://github.com/davidhalter/jedi/issues/1100#issuecomment-383737205).  However, the autocompletion and documentation popup will no longer work for `User.objects.` (and any other Django models).

@jonathanslenders Up until recently, I've been using `shell_plus --ipython`, which has (and still) works by providing tab-completion (but no documentation popup, of course).  With `ptipython`, would it be possible to fallback to `ipython` tab-completion in this situation?  Or is that another security issue that should be avoided?

**Comment by jonathanslenders** [comment]
@myii: Can I close this issue? There is a new Jedi release, and I've done several fixes to ptpython itself.

**Comment by myii** [comment]
@jonathanslenders Thanks for the update, I'll check those out when I get a chance.  I'll go ahead and close this issue.
