### ISSUE TITLE
Decode Error on Interactive mode

### ISSUE THREAD

**Issue by ju-w** [jonathanslenders/ptpython#247]
I have a UTF-8 file that looks like this:

`error.py`

```
a = '”'
```
When I run `ptpython -i error.py`, I get the following traceback:

```
Traceback (most recent call last):
  File "c:\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python36\Scripts\ptpython.exe\__main__.py", line 9, in <module>
  File "c:\python36\lib\site-packages\ptpython\entry_points\run_ptpython.py", line 74, in run
    title='Python REPL (ptpython)')
  File "c:\python36\lib\site-packages\ptpython\repl.py", line 320, in embed
    cli.run()
  File "c:\python36\lib\site-packages\prompt_toolkit\interface.py", line 404, in run
    self.on_start.fire()
  File "c:\python36\lib\site-packages\prompt_toolkit\utils.py", line 60, in fire
    self()
  File "c:\python36\lib\site-packages\prompt_toolkit\utils.py", line 56, in __call__
    handler(self.sender)
  File "c:\python36\lib\site-packages\ptpython\repl.py", line 62, in _on_start
    code = compile(f.read(), path, 'exec')
  File "c:\python36\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2: character maps to <undefined>
```
`python -i error.py` works fine, also `ptpython` and `import error` is no problem.

I get this error under Windows, Linux is fine.

A file containing only:
```
# ”
```
also triggers the issue.

[error.txt](https://github.com/jonathanslenders/ptpython/files/2078096/error.txt)

**Comment by jonathanslenders** [comment]
This looks like a bug. Thanks for reporting!

**Comment by ju-w** [comment]
The bug is caused by this code:

https://github.com/jonathanslenders/ptpython/blob/f565e6a086d3c58415ede6df67046e90f2efe5bf/ptpython/repl.py#L47-L57

because `path` is opened with `'r'` and no encoding specified. Changing it to `open(path, 'rb')` fixes the issue.

However, there are several occurences in the code where the `open` is either `'r'` or `'rb'`

### `'rb'`:

https://github.com/jonathanslenders/ptpython/blob/f565e6a086d3c58415ede6df67046e90f2efe5bf/ptpython/entry_points/run_ptipython.py#L51

https://github.com/jonathanslenders/ptpython/blob/f565e6a086d3c58415ede6df67046e90f2efe5bf/ptpython/entry_points/run_ptpython.py#L55

(Maybe those should be wrapped in a context manager as well?)

### `'r'`:
https://github.com/jonathanslenders/ptpython/blob/f565e6a086d3c58415ede6df67046e90f2efe5bf/ptpython/entry_points/run_ptipython.py#L74

https://github.com/jonathanslenders/ptpython/blob/f565e6a086d3c58415ede6df67046e90f2efe5bf/ptpython/repl.py#L52

https://github.com/jonathanslenders/ptpython/blob/f565e6a086d3c58415ede6df67046e90f2efe5bf/ptpython/repl.py#L258


All of those are compiled and executed.


I can create a pull request and change this, or is there a reason for the current way?

**Comment by jonathanslenders** [comment]
Thanks a lot for digging into this! No, there is no reason for the way it is.
I think best is to open in binary modem, and call decode() manually. Important is to test this on Python 2 as well. Feel free to create a pull request and I'll merge it.
