### ISSUE TITLE
Can't import modules anymore

### ISSUE THREAD

**Issue by r6203** [jonathanslenders/ptpython#248]
I can't import any modules from within my project (venv). I just get a "No module named" error.
This was all working fine a few hours ago... since then I've changed nothing (intentional).

However, importing modules from within the standard Python shell works still fine.

This issue now happens in every project.

I'm using ptpython version 0.41 and Python 3.6.5

Any idea on this?

edit: Seems to be related to #246

**Comment by r6203** [comment]
It seems "jedi" is causing the problems. If I downgrade jedi to 0.11.1 everything is working.

**Comment by hammerheadlemon** [comment]
jedi 0.12 is six months old so jedi is unlikely to be the cause.

Would you be able to test as per [#246](https://github.com/jonathanslenders/ptpython/issues/246)?

* launch `ptpython`
* is your working directory in `sys.path`?
* try to use `import` - if you're seeing the same issue as me, this will remove the empty string from `sys.path[0]`. Check `sys.path` to confirm. Also, try to add your working directory manually: `sys.path.insert(0, '/path/to/your/working/directory') and trying using `import` as normal.

Report back here or at [#246](https://github.com/jonathanslenders/ptpython/issues/246). Many thanks.

**Comment by r6203** [comment]
My working directory isn't in `sys.path` when launching `ptpython`.

If I launch the standard Python shell, `sys.path[0]` contains an empty string (`''`) and the imports are working.

After inserting an empty string into `sys.path[0]`, `ptpython` still isn't able to import local modules. If, however, I insert the absolute path to my working directory, the import works.

As I already said, using `jedi` 0.11.1 doesn't cause this issue. I can reproduce this way:
- `mkdir foo && cd foo`
- `mkdir foo && touch foo/__init__.py && touch foo/bar.py`
- `python -m venv venv`
- `source ./venv/bin/activate.fish` (I'm using fish shell)
- `echo "docopt==0.6.2
jedi==0.11.1
parso==0.2.1
prompt-toolkit==1.0.15
ptpython==0.41
Pygments==2.2.0
six==1.11.0
wcwidth==0.1.7
" > requirements.txt`
- `pip install -r requirements.txt`
- `ptpython`
- `import foo.bar`

Now the import works. If I, however, use jedi==0.12.0, I encounter the import issue.

**Comment by ju-w** [comment]
I can confirm this issue.
Venv is not even required and Jedi==0.11.1 will fix it.

**Comment by zjablonski** [comment]
I can also confirm that reverting to Jedi==0.11.1 resolves the issue.

**Comment by davidhalter** [comment]
This is a Jedi bug. Confirmed in #1148.

**Comment by dwaltrip** [comment]
My temporary hack for this was to add the following to my `~/.ptpython/config.py`

```
@repl.add_key_binding(Keys.ControlN, Keys.ControlN)
def _(event):
    code = 'import sys; sys.path.append("%s");' % PROJECT_DIR
    event.cli.current_buffer.insert_text('\n%s\n' % code)
```

This allows me to simply press `ctrl+n` twice right after loading the repl and then hitting enter to add my project dir to `sys.path`

**Comment by jonathanslenders** [comment]
Hi everyone, I pushed a new version of ptpython that ensures that the current directory is always present in sys.path. This also upgrades to prompt_toolkit 2.0. Can you try again?

**Comment by r6203** [comment]
@jonathanslenders Works. Thank you very much!

**Comment by davidhalter** [comment]
BTW: Jedi was released a week ago. So everything should work without the fix in prompt_toolkit (@jonathanslenders you might be able to remove it again).
