### ISSUE TITLE
only way to leave multiline editing is in vim nav mode

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [jonathanslenders/ptpython#25]
i just played around with emacs and vim modes after pip install
the only way i could use to submit a multiline code chunk was by going to vim nav mode
(python2.7 in a virtualenv)

**Comment by jonathanslenders** [comment]
That's true, but by design. Multiline chunks are always submitted by pressing [meta]+[enter]. (which is either esc+enter or alt+enter) So, in Vi, the meaning of the leading escape is obviously to go into navigation mode, and from there you can just press enter. But of course, even in Vi mode you can press alt+enter any time.

**Comment by RonnyPfannschmidt** [comment]
that mode of operation is confusing - all the other python shells end multiline by pressing return after indent is returned to zero

it feels very unexpected

**Comment by jonathanslenders** [comment]
Possibly, but using meta+enter has quite a lot of advantages. (quicker, overall less cursor movement, pasting of multiline snippets containing newlines is possible.) However, this behaviour is easy to customise and to make it configurable.

**Comment by RonnyPfannschmidt** [comment]
i think the principle of least surprise should apply,
a delay would be fine( so pastes would work) but not accepting the input without extra actions is very confusing (i was quite unhappy and confused about that behavior)

**Comment by jonathanslenders** [comment]
Hi @RonnyPfannschmidt  This has been changed in the meantime. Pressing enter twice at the end of the input will also execute the code. Thanks for the feedback!

**Comment by RonnyPfannschmidt** [comment]
nicely done, thanks
