### ISSUE TITLE
import error with config.py

### ISSUE THREAD

**Issue by alexomics** [jonathanslenders/ptpython#253]
Using the example config.py ([from here](https://github.com/jonathanslenders/ptpython/blob/master/examples/ptpython_config/config.py)) I get a `ModuleNotFoundError`:

```Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ptpython/repl.py", line 244, in run_config
    six.exec_(code, namespace, namespace)
  File "/Users/Alex/.ptpython/config.py", line 8, in <module>
    from prompt_toolkit.key_binding.key_processor import KeyPress
ModuleNotFoundError: No module named 'prompt_toolkit.key_binding.key_processor'
```

`prompt_toolkit.key_binding` is installed, but I don't have the `key_processor` module.

Other info:
- Installed via pip
- Python 3.6
- MacOS 10.13.1

**Comment by achalddave** [comment]
If you would like to use `KeyPress`, you can replace the import with:
`from prompt_toolkit.key_binding.input_processor import KeyPress`

**Comment by SicariusNoctis** [comment]
Looks like it's been renamed to `key_processor`:

```python3
from prompt_toolkit.key_binding.key_processor import KeyPress                                                                                                  
```

**Comment by rizplate** [comment]
it has been renamed to input_processor
`from prompt_toolkit.key_binding.input_processor import KeyPress`
