### ISSUE TITLE
why still required prompt-toolkit-1.0.15 

### ISSUE THREAD

**Issue by copdips** [jonathanslenders/ptpython#256]
Hello,

it's strange that although in the setup.py, it gives `'prompt_toolkit>=2.0.0,<2.1.0',`
https://github.com/jonathanslenders/ptpython/blob/master/setup.py#L25.

But when I install by using pip install ptpython, it is prompt-toolkit-1.0.15 installed.

**Comment by IwoHerka** [comment]
That's because latest master has version `0.36` in `setup.py` even though it's tagged under `0.41`. 

You can install master version using `pip install git+https://github.com/jonathanslenders/ptpython.git`. This will pull `prompt_toolkit>=2.0.0`.

However, to get it to work you will have to comment out `SwapLightAndDarkStyleTransformation`, `ConditionalStyleTransformation`imports from `python_input.py` file (and related code).

**Comment by copdips** [comment]
@IwoHerka 

Thx a lot for your reply. It works now.
I cannot test everything in ptpython, only issue that I found is I cannot quit the ptpython prompt by the standard `ctrl+z`, instead I should use `exit()` to quit.

The lines to be commented out are : 
https://github.com/jonathanslenders/ptpython/blob/master/ptpython/python_input.py#L23
https://github.com/jonathanslenders/ptpython/blob/master/ptpython/python_input.py#L536-L538

**Comment by jonathanslenders** [comment]
Right, the latest master branch here requires as well the latest prompt_toolkit branch from GitHub. I hope to push a new release soon (for both projects).

**Comment by copdips** [comment]
A new release sounds great, as I use both PtPython and PyVim, but they cannot co-exit in the same env as they don't require the same version of prompt_toolkit.

**Comment by ned2** [comment]
Cool, would be great to see a new release. ipython and ptpython currently have irreconcilable version requirements for prompt-toolkit, which I think the only good option for working around currently is installing from github?

**Comment by jonathanslenders** [comment]
Hi everyone, I pushed new version of prompt_toolkit, ptpython and pyvim to Pypi. 
One of the reasons it took so long was because I wanted to push it around the same time as IPython (which was earlier this week). So, I'm closing this issue.

**Comment by copdips** [comment]
@jonathanslenders 

Thx for the release, both pyvim and ptpython work well in the same env now.
But I also have to upgrade prompt-toolkit from v2.0.4 to v2.0.5, I'm on windows 10.
