### ISSUE TITLE
How to use within a virtual environment?

### ISSUE THREAD

**Issue by BoltzmannBrain** [jonathanslenders/ptpython#260]
Is it possible to start a ptpython session while in a virtualenv, where it doesn't use the system python?
Note this is with ptpython installed in my system packages, not within the virtualenv.
For example, one can do `virtualenv --python /path/to/my/python` to specify the interpreter. Is something is similar possible w/ ptpython?

**Comment by jonathanslenders** [comment]
Yes, it is possible.
ptpython has to be installed in each virtualenv. Do this by going into the virtualenv and use "pip install".
Then, once you are in the environment and type "ptpython" it will use that virtualenv.

**Comment by BoltzmannBrain** [comment]
Thanks, although that is something I wanted to avoid.
If I do install ptpython in each virtualenv, will my custom settings at `~/.ptpython/config.py` still be used?

**Comment by jonathanslenders** [comment]
Yes, they will still be used.
Actually, for other Python shells like bpython and IPython, the same applies. They have to be installed in the environment.

**Comment by jonathanslenders** [comment]
I'm closing this, if you don't mind. Feel free to open again if needed.

**Comment by drkvogel** [comment]
As per https://github.com/prompt-toolkit/ptpython/issues/77#issuecomment-341876065, you might need to do `hash -r` or similar to make sure you're using the new command in the venv rather than the older one in the search path.

**Comment by YodaEmbedding** [comment]
If `ptpython` opens the system ptpython, try `python -m ptpython` from within the virtual environment, after `pip install -e ptpython`, of course.
