### ISSUE TITLE
New version has import errors

### ISSUE THREAD

**Issue by afrieder** [jonathanslenders/ptpython#263]
Hey there, I'm super excited about the new version of both prompt_toolkit and ptpython. I just installed the newest versions of both, as well as iPython (pip list shows `prompt_toolkit==2.0.5`, `ptpython==2.0.1`, `ipython==7.0.1`). Upon trying to launch ptpython I get various import errors: 

`ImportError: cannot import name 'PathCompleter' from 'prompt_toolkit.contrib.completers'` since https://github.com/jonathanslenders/ptpython/blob/6c0b99ea2b4be963b42c1062b2f33880ba30b6d3/ptpython/ipython.py#L14 is still using the old path for `PathCompleter` and `WordCompleter`, and fixing that raises an issue with https://github.com/jonathanslenders/ptpython/blob/9b61c9941bd4a5dff61c7bbb03172b0a515ee83b/ptpython/ipython.py#L19 since `CommandLineInterface` has been removed. 

Is there a newer version of this file which supports prompt_toolkit 2.0?

**Comment by syslot** [comment]
Also this problem. It should be caused by the new version  prompt_toolkit

**Comment by jonathanslenders** [comment]
Thanks! I just realised this issue is about ptipython, which is broken indeed. IPython and ptpython should work in the same environment. I'll fix it asap.

**Comment by stonebig** [comment]
any hope short term ? it's too tricky to do for non-specialist

**Comment by jonathanslenders** [comment]
This should fix it: https://github.com/jonathanslenders/ptpython/commit/447f9953d91de95e91e53ba8236ef0451b83e410

**Comment by stonebig** [comment]
look indeed ok now.

**Comment by afrieder** [comment]
Yup, fixed! Thanks for the swift response

**Comment by shaypal5** [comment]
This happens to me with `ptpython==2.04` and `prompt_toolkit==2.0.8`. :(
