### ISSUE TITLE
Different Colorscheme

### ISSUE THREAD

**Issue by dufferzafar** [jonathanslenders/ptpython#27]
I am not happy with the current colorscheme of ptpython, so I tried changing the colors present in file `/usr/local/lib/python2.7/dist-packages/ptpython/style.py` but restarting ptpython resulted in no change. Am I doing something wrong? 

IMHO, there should be an easier way to change colors.

**Comment by jonathanslenders** [comment]
Normally, it should indeed be enough to change only that file. I'm not sure why it's not working. If you do ``import ptpython.style; print(ptpython.style.__file__)``, is it that file what you're seeing?

But having a way to easily change the colors is on my to-do list.

**Comment by jonathanslenders** [comment]
Hi @dufferzafar,

The latest version that was released yesterday allows custom color schemes. Please have a try.
See also this ticket: https://github.com/jonathanslenders/ptpython/issues/45

And this configuration file for an example of creating color schemes: https://github.com/jonathanslenders/ptpython/blob/master/examples/ptpython_config/config.py

Cheers,
Jonathan

**Comment by zjjott** [comment]
@jonathanslenders  custom color schemes work at `ptpython` and `ptipython`,but is not good at Django:`./manage shell_plus`，How should I place `config.py` or startup with some params?
