### ISSUE TITLE
multiple python versions

### ISSUE THREAD

**Issue by abottorff** [jonathanslenders/ptpython#29]
There seems to be no way to switch python versions for ptpython. I have 2.7 and 3.4 installed concurrently. If I use pip I can reinstall whichever one i need to use and it'll work that way, but then I have to use pip every time I need to switch. Is there a better way to handle this?

**Comment by ntnn** [comment]
You can directly run the entry points, e.g. through an alias. I.e.:

```shell
alias ptpython2='python $HOME/.local/lib/python2.7/site-packages/ptpython/entry_points/run_ptpython.py'  
alias ptpython3='python $HOME/.local/lib/python3.4/site-packages/ptpython/entry_points/run_ptpython.py'
```

The only other way would be to change the setup.py to change the name of the entry point according the version.

**Comment by abottorff** [comment]
Yeah, I guess since they're actually python packages installed under each version, aliases would be the way to go. Thanks.
