### ISSUE TITLE
function signature hint toolbar doesn't appear in windows

### ISSUE THREAD

**Issue by darikg** [jonathanslenders/ptpython#30]
Hi, in [this screenshot](https://raw.githubusercontent.com/jonathanslenders/ptpython/master/docs/images/multiline.png) it looks like ptpython is hinting the argument list to the currently typed function. I've been playing around with ptpython and am unable to trigger this feature. So, two questions -- How do I enable function hinting in ptpython, and second, where/how is the hinting accomplished in the source code?

Thanks!

**Comment by ntnn** [comment]
It should come up itself, without a trigger, and the engine in question is [jedi](http://jedi.jedidjah.ch/en/latest/).

**Comment by darikg** [comment]
I just tried in a linux VM and it does show up automatically without a trigger like you said. But it never shows up in Windows.

For the source code, I meant where specifically does ptpython define the corresponding controls. Grepping for 'jedi' got me to ptpython/layout.py, which defines classes SignatureControl and SignatureToolbar, which I think is exactly what I'm looking for. Thanks!

**Comment by jonathanslenders** [comment]
Hi, I'm not aware of any differences between Windows and Linux, but I'll try as soon as I have access to a Windows machine again.

The Engine behind is indeed Jedi, and currently there's also some heavy development going on for that project, so I suspect if there are any issues with Jedi, that things will quickly get even much better.

**Comment by darikg** [comment]
I've been playing around a little bit more with ptpython in linux and windows, and the even more striking difference between the two is that the autocomplete menus show up automatically in linux, but only upon the `tab` key in windows.

I think maybe the fact that the function signatures don't show up in windows is a more general issue with python-prompt-toolkit where one of the CommandLineInterface EventHooks (presumably onInputTimeout) isn't being fired. This difference in autocomplete behavior is also present in prompt-toolkit/examples/autocompletion.py. I tried to follow the onInputTimeout logic around in prompt-toolkit but I'm not very familiar with asyncio and got lost pretty quickly.

Thanks for your time and if there's anything I can do to help track this down please let me know.

**Comment by jonathanslenders** [comment]
Hey @darikg, thanks for pointing out. Now I remember there were indeed some issues in the Windows event loop. Not in the timeout itself, but in the call_from_thread implementation.

I have a new look asap. The last two weeks, I've been very busy, but I hope to continue development very soon!

**Comment by jonathanslenders** [comment]
Fixed by: https://github.com/jonathanslenders/python-prompt-toolkit/issues/119
