### ISSUE TITLE
is support  module reload

### ISSUE THREAD

**Issue by rfyiamcool** [jonathanslenders/ptpython#36]
is support  module reload

**Comment by jonathanslenders** [comment]
No. I'm sorry. If you are on Python2, there is the ``reload()`` function that you can use. On Python3 there is no such thing. It's not reliable, and better is to restart the repl.

Maybe in the future we will have a more user friendly way to reexecute all the commands.

**Comment by jonathanslenders** [comment]
I'm closing this one, because module reloading is probably not something we will ever encourage or support. Sorry about that.
