### ISSUE TITLE
"from __future__ import division" does not work

### ISSUE THREAD

**Issue by Quotation** [jonathanslenders/ptpython#38]
In `ptpython` REPL, input:
```
from __future__ import division
print 1/2
```
got output `0`.
But in standard `python` REPL, the output is `0.5`.

**Comment by jonathanslenders** [comment]
Hi @Quotation,

You are right, this is a bug.
I'm not sure what the correct way to solve this is. I can see that 'division' appears as a ``_Feature`` instance in the globals. But I've no idea how to use ``exec()`` or ``eval()`` using these features.

The same issue appears with ``unicode_literals``.

**Comment by Quotation** [comment]
Hi @jonathanslenders,

I find a way to use __future__ in `exec()` and `eval()`.
From the documentation of `_Feature`:
> CompilerFlag is the (bitfield) flag that should be passed in the fourth argument to the built-in function compile() to enable the feature in dynamically compiled code. This flag is stored in the compiler_flag attribute on _Feature instances.

So instead of using simple `eval`, we use `eval` with `compile` with `_Feature.compiler_flag`.
```Python
from __future__ import division
eval(compile('1/2', '<string>', 'eval', division.compiler_flag))
```
The output is `0.5`.

But I still have no idea about how to get *all* imported CompilerFlags. There is a simple solution, we can check `globals()` for `division, unicode_literals, print_function` and so on. But if a user assigns another value to global symbol `division`, we can't know that `__future__.division` is already imported.

**Comment by jonathanslenders** [comment]
Thanks @Quotation.

It's now implemented: https://github.com/jonathanslenders/ptpython/commit/59382a12f8e0ffc20fe21f37bd2e8a958650385d
(Note that this requires the latest master commit of ``prompt_toolkit``. I hope to do a new Pypi release somewhere this or next week.)

Jonathan

**Comment by jonathanslenders** [comment]
This has been released yesterday. Thanks @Quotation.

**Comment by Quotation** [comment]
Cool. Thanks.
