### ISSUE TITLE
feature request, for a better completion experiments.

### ISSUE THREAD

**Issue by hackrole** [jonathanslenders/ptpython#39]
hi, the ptpython is really awesome. the line edit was always what I want. the vi/emacs keybinds really go beyond my hope for python-shell. 

the complete is beautiyf too. use the old ipython, the completion always pollute my screen too much.
but there was a problem, most time I really donot remember what the attr or function I was looking for. the old ipython give all of it, so I may choose. the ptipython give only some of it, I have to <tab><tab>... to   
look through it. that's not good.

I request you may look at the zsh completion. It output all the output under the current cursor but not pollute the screen, and when you finish edit, it clear the completion-output.

**Comment by jonathanslenders** [comment]
Hi @hackrole,

Thanks for the feature request! I understand what you are asking for. This is not my priority, but I'll have a look how to do this. It's only a matter of visualisation. (I think the fish shell does it as well.)

Jonathan

**Comment by jonathanslenders** [comment]
Hi @hackrole,
Now we have multi-column completions as an option:
![capture d ecran 2015-07-15 a 13 13 41](https://cloud.githubusercontent.com/assets/216638/8697228/b23b1782-2af3-11e5-8899-0b2c9a5c9826.png)

You can change it from the configuration menu, or if you want this to be the default. Have a look at this setting:
https://github.com/jonathanslenders/ptpython/blob/master/examples/ptpython_config/config.py#L28

**Comment by hackrole** [comment]
I have saw this. It is really wonderful.

**Comment by jonathanslenders** [comment]
Thanks!
