### ISSUE TITLE
Autocomplete doesn't work on windows

### ISSUE THREAD

**Issue by ionelmc** [jonathanslenders/ptpython#40]
I've installed it on windows 8.1 and python 2.7.9. Output is colored and everything but I don't get any autocompletion. I tried pressing TAB - is autocomplete bound to a different key?!

**Comment by jonathanslenders** [comment]
Hi @ionelmc,

Can you please check again with the latest version?

If it's the same issue as https://github.com/jonathanslenders/python-prompt-toolkit/issues/119
and https://github.com/jonathanslenders/ptpython/issues/30

Then it's fixed.
Thanks.
Jonathan

**Comment by ionelmc** [comment]
It works now :grin:
