### ISSUE TITLE
add banner argument in ptpython.repl.embed

### ISSUE THREAD

**Issue by dakra** [jonathanslenders/ptpython#41]
There is no option to display a banner text when instantiating a new shell from `ptpython.repl.embed`.
Both `IPython.terminal.embed.InteractiveShellEmbed` and `bpython.embed` have a banner argument that I can pass a text to display to.

**Comment by jonathanslenders** [comment]
Thanks @dakra  for the feature request. This shouldn't be too hard to do, maybe I find some time next week. Jonathan

**Comment by jonathanslenders** [comment]
What do you exactly expect from the banner?

If it's just a print statement in front, you can create your own ``embed()`` function that does this:

```python
def embed_with_banner(globals, locals, banner):
    print(banner)
    embed(globals, locals)
```

**Comment by dakra** [comment]
Hmm, not sure why I didn't think of that.
After looking at ipython.embed it does just that (they use stdout.write which is the same).
I'll just use print then.. so I don't mind if you close this ticket.
Thanks :)

**Comment by jonathanslenders** [comment]
Ok. It's great to see Pyramid integration by the way!

Maybe in a future version, I'll make the status bar more customizable. I think it would be nice to show some additional info there. But I have to think of a good API to support all the customizations that people like.

Closing this for now.
