### ISSUE TITLE
Interactive mode with ptipython

### ISSUE THREAD

**Issue by NamanJn** [jonathanslenders/ptpython#50]
<code> ptipython --vi --interactive=&lt;file_name&gt;</code>

I cannot seem to get this working. Am I missing something or this feature does not exist?

**Comment by NamanJn** [comment]
Ok well it does not exist. Is it possible to add the interactive option?

**Comment by jonathanslenders** [comment]
Hi @NamanJn ,

Sure we can do that.
I'll put it on my todo list. This is a small, useful thing to have.

Jonathan

**Comment by jonathanslenders** [comment]
Implemented: https://github.com/jonathanslenders/ptpython/commit/30a08e7996f4a6feec60a126f48019a69125e257

**Comment by NamanJn** [comment]
Hey Jonathan thanks for implementing it! However, I tried but could not change directories with the <code>cd </code> command inside the ptipython interpreter.

**Comment by jonathanslenders** [comment]
Hi NamanJn, that's another bug. Thanks for telling. I created a ticket for this: https://github.com/jonathanslenders/python-prompt-toolkit/issues/143

For now, if you add the leading %, then it works. E.g. ``%cd /some/path``.
