### ISSUE TITLE
It is better if ptpython support pyenv

### ISSUE THREAD

**Issue by axiaoxin** [jonathanslenders/ptpython#51]
I usually use pyenv, when I switch from python2 to python3, the ptpython still python2

**Comment by jonathanslenders** [comment]
Probably you have install ptpython system wide instead of inside the virtualenv. ptpython will always use the virtualenv in which it was installed. Activate the python3 virtualenv, then run ``pip install -U ptpython`` and try again.

**Comment by axiaoxin** [comment]
ptpython  installed system wide

**Comment by jonathanslenders** [comment]
So does it work now after installing it in the virtualenv?

**Comment by axiaoxin** [comment]
Sorry, maybe I don't explain this clearly. pyenv is simple python version management https://github.com/yyuu/pyenv

Using it to switch python version conveniently, it has nothing to do with the virtualenv

**Comment by axiaoxin** [comment]
just like nodes's nvm

**Comment by jonathanslenders** [comment]
Ok, so if I understand correctly, calling ``python`` refers to the calling the new interpreter.

Use instead:
```
python -m ptpython
```

You could make it an alias:
```
alias ptpython="python -m ptpython"
```

**Comment by Congee** [comment]
@jonathanslenders Then, how do you run ptipython in this way?
