### ISSUE TITLE
ptpython can't import a local package named `test`

### ISSUE THREAD

**Issue by obmarg** [jonathanslenders/ptpython#53]
I've got a 'test' package in the top-level of my project that I'm trying to import a file from, but ptpython (and ptipython) won't let me.  It seems to be picking the `test` package from the python standard library instead.  Plain python (and plain ipython) do not have this problem.  This is on python3, though I haven't tested with python2.

Steps to reproduce:

```
$ mkdir python-test
$ cd python-test
$ mkvirtualenv -p /usr/local/bin/python3 python-test
$ pip install ptpython
$ mkdir test
$ touch test/__init__.py
$ touch test/schema_data.py
```

And demonstration of the bug:
```
$ python
Python 3.4.1 (default, Aug 24 2014, 21:31:55)
[GCC 4.2.1 Compatible Apple LLVM 5.1 (clang-503.0.40)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import test.schema_data
>>> quit()
$ ptpython
In [1]: import test.schema_data
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'test.schema_data'
No module named 'test.schema_data'

In [2]: import test

In [3]: test
Out[3]: <module 'test' from '/usr/local/Cellar/python3/3.4.1_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/test/__init__.py'>
```

**Comment by jonathanslenders** [comment]
Hi @obmarg,

Thanks for reporting and the instructions to reproduce.
It should be fixed in the next release: https://github.com/jonathanslenders/ptpython/commit/549ddd38d28dd21a5cd41caac399a0fd0210f56c

Jonathan
