### ISSUE TITLE
Provide an ability to configure hotkeys

### ISSUE THREAD

**Issue by dangusev** [jonathanslenders/ptpython#54]
Hello. I've got a problem with "Execute" (Meta+Enter) in Paste mode because I'm using i3wm and the same hotkeys already assigned to "Open terminal" command. I'm sure that I'm not the only one who have this issue. Can you consider this improvement? Thanks!

**Comment by jonathanslenders** [comment]
HI @dangusev,

It is possible to configure hotkeys. Have a look at the example configuration file. I just added an example to have an alternative for Meta+Enter.
https://github.com/jonathanslenders/ptpython/blob/340164547fefef35dd304f554adccbc9edee2efd/examples/ptpython_config/config.py#L90

Jonathan

**Comment by dangusev** [comment]
Thanks for your response! I should read docs more carefully next time)
