### ISSUE TITLE
how can I specify the python version used by ptpython

### ISSUE THREAD

**Issue by bluealert** [jonathanslenders/ptpython#58]
can I config it? I cannot find this configuration in https://github.com/jonathanslenders/ptpython/blob/master/examples/ptpython_config/config.py

**Comment by jonathanslenders** [comment]
Hi @bluealert,

ptpython starts with the Python version defined by the python executable. Basically whatever ``/usr/bin/env python`` returns.

If you want to run it using Python2, while Python3 is the default, type ``python2.7 -m ptpython``.

In general, it's recommended to use virtualenvs. ptpython will run using the Python version of the active virtualenv.

Jonathan

- To do: add documentation to README.

**Comment by bluealert** [comment]
sorry, I want to run ptpython using Python3, but I can not.

```
python3 -m ptpython

/Library/Frameworks/Python.framework/Versions/3.4/bin/python3: No module named ptpython.__main__; 'ptpython' is a package and cannot be directly executed
```

**Comment by bluealert** [comment]
after I run `pip3 install ptpython --upgrade`. It's ok now. Thank you. :)

**Comment by liborw** [comment]
Is this supposed to work for ptiptyhon as for me the `ptipython` works fine, but
```
$ \python -m ptipython
/usr/bin/python: No module named ptipython
```

**Comment by shaypal5** [comment]
I have a virtual env (managed by conda, not by virtualenv) with python 3.5.2 installed. Running `python --version` shows 3.5.2, and running `ipython` opens an ipython 3.5.2 shell, but running ptipython results in a 2.7.6 python shell, which is the version that comes with the machine.

I haven't run into this before, although I had a similarly configured virtual environment (with conda) and used ptipython extensively.

**Comment by jonathanslenders** [comment]
``python -m ptipython``, that does indeed not work, because the Python package is called ``ptpython``.

Alternatively, I could probably implement any of the following:
```
python -m ptpython --ipython
python -m ptpython --ptpython
python -m ptpython.ptipython
```
Would that work?

**Comment by shaypal5** [comment]
Sounds like it will help liborw's problem, yup.

I'd still love a way to understand and config the python and/or the Ipython executable the ptpython uses when you start it. Any chance of this going into the config.py?

**Comment by jonathanslenders** [comment]
Normally, running ``ptipython`` should run the same executable as running ``ptpython``.
There is no way to put this in config.py, because at the time where this configuration is read, we already have a Python interpreter running.
I think that if both IPython and ptpython are installed in the current virtualenv, then it should run fine.
