### ISSUE TITLE
Custom Dynamic Prompt with PtPython

### ISSUE THREAD

**Issue by valencra** [jonathanslenders/ptpython#66]
Hello Jonathan,

Would it be possible to have a feature where an embedded PtPython instance can actively "listen" to a variable from where the instance was created, and then alter the prompt's output based on that variables changing values? I have an instance of a class in the "if __name__ == '__main__''" section of the module when it is being run in interpreted mode, and the user can alter some of its attributes by typing in certain commands or functions. I would like to dynamically change the prompt to display what the current value of those instance attributes are. The attributes whose values have to be displayed in the prompt are known in advance. Please let me know if this is possible with the current PtPython.

Thank you,
Robert Valencia

**Comment by jonathanslenders** [comment]
This should be possible, with a small change. I'll put it on the to-do list.

**Comment by jonathanslenders** [comment]
Could you have a look at the following pull request and have try?
https://github.com/jonathanslenders/ptpython/pull/67

**Comment by valencra** [comment]
Hi Jonathan,

My apologies for the late reply. I tried it out and it works! Thank you so much :) 

I would also like to ask about your rules on altering copies of your PtPython package. I would like to alter my copy to remove the 'In[#]' part of the prompt (which is part of the layout.py module), and I am just wondering if this is okay for personal/business use.

Thanks again.

**Comment by jonathanslenders** [comment]
Hi @valencra,

Maybe I should make it more flexible that the ``In[#]`` part can be overriden as well.

In any case, feel free to fork it, play around with it as much as you want. That's ok, even for business use. (But better of course is that this repository has all the flexibility you need. Maintaining a fork and keeping it up to date takes some effort.)

Jonathan

**Comment by ryneeverett** [comment]
Reminder: `In[#]` part can already be overriden in pt**i**python via the ipython setting `c.PromptManager.in_template`.

**Comment by valencra** [comment]
@jonathanslenders Thank you for the permission, Jonathan! I have been looking for a package like this for quite some time now, and this is the only one that meets all of my needs, so thank you for sharing your work.

@ryneeverett That is true. Although, for now, I have altered my copy of PtPython.

**Comment by jonathanslenders** [comment]
@ryneeverett: That's true, but for now I'm still ignored that, because the IPython template is not yet compatible. (The way IPython handles colors needs to be improved.)

@valencra: I made a second pull request. It's an alternative implementation, and probably I'm going for that one. Please have a look:
https://github.com/jonathanslenders/ptpython/pull/68

**Comment by valencra** [comment]
@jonathanslenders: I tried it out and it's great! Thanks again. As another suggestion, maybe in the future,  an option to change the colour scheme would also be nice.

**Comment by jonathanslenders** [comment]
Changing the colorscheme is already possible.

Have a look at this example configuration file: https://github.com/jonathanslenders/ptpython/blob/797e61ee54bd82730d246f660e445e4730a0041a/examples/ptpython_config/config.py#L81

The ``configure()`` function that you see there is the same as the following ``configure`` function:
https://github.com/jonathanslenders/ptpython/blob/797e61ee54bd82730d246f660e445e4730a0041a/examples/python-embed-with-custom-prompt.py#L12

Cheers.

**Comment by valencra** [comment]
Oh wow what was I thinking I did not realize that. I originally altered the hex codes in the style module, but now that I know this, I will change it today. Thanks again @jonathanslenders !

**Comment by jonathanslenders** [comment]
You're welcome!

I can close this issue, right?

**Comment by valencra** [comment]
Yes :)
