### ISSUE TITLE
Display docstring of all objects

### ISSUE THREAD

**Issue by azag0** [jonathanslenders/ptpython#72]
It seems that the docstring is not displayed for all types of objects with `show_docstring = True`. My guess would be that it is displayed only for function objects? But the docstring might be present in other objects, in my case it is the fortran object from f2py. The wrapped fortran functions have a useful auto-generated docstring (documenting the function interface) and it would be very helpful to see it.

**Comment by jonathanslenders** [comment]
Hi @azag0,
Docstrings are coming from the Jedi library. I'm not entirely sure how it works, but this could also be a bug or shortcoming in Jedi. I'm not sure what scenarios are supported.

**Comment by azag0** [comment]
I'm not sure since when, but it works now, probably updated in Jedi?
