### ISSUE TITLE
Add --pylab mode for ptipython ?

### ISSUE THREAD

**Issue by Naereen** [jonathanslenders/ptpython#75]
I found no easy way to allow `ptipython` to launch `ipython` with the [`--pylab` mode](http://matplotlib.org/users/shell.html#ipython-to-the-rescue).

Could you add `--pylab` as an accepted command-line option (and pass it to `ipython`)?
Thanks in advance.

**Comment by fredcallaway** [comment]
For what it's worth, the IPython team does not advise using --pylab. However, you can achieve almost what you want by simply typing `%pylab` at the beginning of your interactive session.

**Comment by Naereen** [comment]
OK. However, could you try to add the ``--pylab`` option please ?
