### ISSUE TITLE
Does not recognize some built-in functions

### ISSUE THREAD

**Issue by thudfoo** [jonathanslenders/ptpython#83]
Neither **reduce** nor **reload** for instance.

**Comment by jonathanslenders** [comment]
What Python version are you using? Sure it's not python3?

Both reduce and reload are deprecated and have been removed from Python3.

**Comment by thudfoo** [comment]
I am using ptpython with python3.4 but checked reduce using python2.7.  Not a bug!

**Comment by thudfoo** [comment]
On Fri, Nov 20, 2015 at 7:27 AM, Jonathan Slenders <notifications@github.com
> wrote:

> What Python version are you using? Sure it's not python3?


​Python3.4. I closed the issue at github. Sorry for the noise but thanks
for ptpython.​



-- 
I have seen the future and I'm not in it!
