### ISSUE TITLE
ptipython with barry_as_FLUFL from future

### ISSUE THREAD

**Issue by feigaochn** [jonathanslenders/ptpython#86]
The code snippet is reported a syntax error on `>` by **ptipython** and can not executed.
```python
In: from __future__ import barry_as_FLUFL
In: 1 <> 2
```

It works as expected in ptpython, python, and ipython.
```Python
Out: True
```

Env:
Python 3.5.0
IPython 4.0.0
ptpython 0.25

**Comment by jonathanslenders** [comment]
Hi @feigaochn,

Thanks for reporting this bug!
This should fix it: https://github.com/jonathanslenders/ptpython/commit/a32e44c17fcc7e10624c3476fe1042779c587bdc

Jonathan
