### ISSUE TITLE
ptpython breaks all iTerm2 keybinds

### ISSUE THREAD

**Issue by hassek** [jonathanslenders/ptpython#90]
after I run ptipython all my iTerm2 keybinds get broken (for example, I can't do Ctrl-a to jump to the start of the line) 

This gets fixed by reseting the bash shell with *reset* but is still kind of a pain.

**Comment by hassek** [comment]
I guess everyday you learn something, [here](http://superuser.com/questions/316668/ctrl-a-doesnt-work-in-bash-terminal-on-os-x-lion) is what happened.

I think that not changing this values, if possible, would be handy. If there is no other way to make ptpython work with vi but changing this, we should add this information to the docs.

**Comment by hassek** [comment]
it was something else I added in my .inputrc

**Comment by jonathanslenders** [comment]
Glad you found it! :)

``set -o vi/emacs`` does not influence ptpython (or any of the prompt_toolkit based applications.) It's for readline only.

If you want to have Vi mode in ptpython, add the following line to your configuration file:
https://github.com/jonathanslenders/ptpython/blob/master/examples/ptpython_config/config.py#L62

**Comment by hassek** [comment]
Heh yea I figured out, I just played with readline and ptpython at the same
time and ended up thinking it was ptpython, which btw, fixed a lot of my
common PITA's with the python shell, thanks for this great tool!
