### ISSUE TITLE
<Up> in ptipython does not do history substring search

### ISSUE THREAD

**Issue by Wilfred** [jonathanslenders/ptpython#96]
In ipython, I can do the following:

```
In [1]: x = 1 + 1

In [2]: y = 2 + 2

In [3]: x = <up arrow key on keyboard>
```

and ipython completes it to `x = 1 + 1`. I can't see any way of doing this in ptipython.

**Comment by jonathanslenders** [comment]
Hi @Wilfred,

In ptipython, go to the Menu (Press F2) and turn history search on.
To make this setting persistent, save this in the config: https://github.com/jonathanslenders/ptpython/blob/master/examples/ptpython_config/config.py#L76

Hope that works,
Jonathan

**Comment by ryneeverett** [comment]
Cool, I didn't know about that feature. It seems like the `enable_history_search` and `complete_while_typing` features could be compatible if history search was disabled in insert mode since completion is already insert-mode-only.

**Comment by Wilfred** [comment]
Thanks, that works nicely.
