### ISSUE TITLE
Weird PyQt behavior

### ISSUE THREAD

**Issue by kernc** [jonathanslenders/ptpython#98]
With ptipython, the following produces an empty, widget-less window (or so it appears):
```python
import pyqtgraph.examples as ex
ex.run()
```
In IPython, the same code works as expected.

How would I debug this further or can you try it?

**Comment by jonathanslenders** [comment]
Hi @kernc,

Thanks for reporting this issue! I guess this could be, because we don't have an importhook for Qt registered. Could you try and see whether this works on the latest 'master' commit of IPython, by checking out their repository?

Thanks,
Jonathan

**Comment by JohnLunzer** [comment]
I will add my experience to this. When I attempt:
```python
import pyqtgraph as pg
pg.image()
```
Which should create a blank image window. I get nothing. When I execute ```pg.image()``` again a single PyQt window appears but it is in a frozen state. Subsequent executions of ```pg.image()``` will show an additional PyQt window in a frozen state.

I am running IPython 4.2.0 release from April 20th (12 days ago) which is the most recent version available with anaconda as of this posting. Hopefully this can satisfy your previous request.

I really love ptpython, integration with PyQt would be great.

**Comment by jonathanslenders** [comment]
Hi @JohnLunzer,

Thanks for sharing your experience. I really appreciate it.

Qt integration should clearly improve. Currently I'm working with the IPython team on the console UI which will use prompt-toolkit. This involves also having input hooks required for nice Qt integration. (I believe that part is already done.) When finished, I can update ptipython to get the best of everything.

Jonathan

**Comment by kernc** [comment]
FWIW this late, my above `pyqtgraph.examples.run()` code works on current IPython master as well as ptipython wrapping it, it seems. Thanks.

I can reproduce @JohnLunzer's issue with pure IPython, but I can also work around it with [some documented magic](https://ipython.org/ipython-doc/stable/interactive/reference.html#gui-event-loop-support):
```python
%gui qt
```

**Comment by JohnLunzer** [comment]
Coming back to this pretty late but I recently updated ptpython and I'm still seeing the same behavior even if I use the `%gui qt` magic prior to invoking pyqtgraph. Also using IPython 5+

There is probably still room for improvement for PyQt integration.
